### ISSUE TITLE
Create Routable BC Maker

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#102]
Routable BC Maker is a Java application that takes a snapshot of all static routing data from GeoBC and participating BC road authorities, and creates Routable BC, a set of data files that can be loaded by the BC Route Planner NG on startup. Creating Routable BC Maker will involve implementing and extending the functionality currently residing in FME data prep scripts. Routable BC Maker needs road segment names and geometries, traffic impactors, one-way indicators, turn restrictions, height and weight restrictions, policy-based road restrictions,  designated truck routes, historic traffic congestion, and ferry schedules. Real-time data such as current traffic congestion, road accidents and ferry delays is out of scope.

**Comment by cmhodgson** [comment]
This has been completed as planned for milestone 4 but policy-based road restrictions are not currently in scope.
