### ISSUE TITLE
Add support for a turnCosts parameter

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#104]
A turnCosts parameter allows each route request to define its own turn costs.

UPS penalizes left-turns heavily to reduce fuel costs and make route time more deterministic. See https://www.cnn.com/2017/02/16/world/ups-trucks-no-left-turns/index.html

turnCosts takes 3 values separated by commas: no-turn cost, right-turn cost, and left-turn cost. All costs are given in seconds. Here are some examples:

1. turnCosts=3,9,27 means no-turns take 3 s, right-turns take 9 s, and left-turns take 27 s
2. turnCosts=5,10,20 means no-turns take 5 s, right-turns take 10s, and left-turns take 20 s

Turn costs vary by type of traffic impactor so how should this be accommodated?

Adding this parameter to the demo app UI will allow us to gain sufficient experience to determine appropriate default values.

**Comment by alixcote** [comment]
This exists now in the demo app. Need to update production documentation.

Example: globalDistortionField=alleyway:1.2,alleyway.truck:1.1,arterial_major:1.01,arterial_major.truck:1.01,arterial_minor:1.01,arterial_minor.truck:1.01,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:1.2,driveway.truck:1.1,ferry:1,ferry.truck:1,freeway:1,freeway.truck:1,highway_major:1,highway_major.truck:1,highway_minor:1,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.1,local.truck:1.05,ramp:1,ramp.truck:1,recreation:1.2,recreation.truck:1.1,resource:1.2,resource.truck:1.1,restricted:1.2,restricted.truck:1.1,service:1.2,service.truck:1.1,strata:1.2,strata.truck:1.1,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3.0,10.0,7.0,1.2&turnCost=5.0,1.0,10.0,5.0
