### ISSUE TITLE
Move truck parameters into separate resources 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#108]
router/truck/distance
router/truck/route
router/truck/directions
router/truck/optimalRoute
router/truck/optimalDirections

**Comment by cmhodgson** [comment]
Done, currently these are just aliases for their non-truck counterparts. Note that there is no "optimalDistance" resource, nor the "/truck/optimalDistance" suggested above.

**Comment by cmhodgson** [comment]
These resources should be added to the web service definition file so they can be tested with the api console.
