### ISSUE TITLE
In turn-restriction editor, display type of turn restriction in editing panel

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#109]
In editing panel, when a turn restriction is selected, add the type of turn restriction (e.g., No Left, No Right). Its not always clear from the map which restriction is being edited.

**Comment by gleeming** [comment]
The right turn cases are being displayed with text indicating straight -- probably a minor copy/paste bug.

**Comment by cmhodgson** [comment]
right turns now being displayed correctly. Still need to decide what approach to take for the icons, possibly a dual outline (halo) in both light and dark to ensure they are visible on both light and dark backgrounds.

**Comment by cmhodgson** [comment]
The type of turn restriction has been added but the turn restriction icon changes are to be pushed to the next sprint milestone, with the other turn restriction review tool tasks.
