### ISSUE TITLE
Update route optimizer to  ignore time-dependency

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#115]
Take the following into account:
 - unconditional turn-restrictions
 - turn costs
 - truck dimension-based  turn-restrictions

Ignore time-dependent turn-restrictions

**Comment by cmhodgson** [comment]
Note, this also ignores traffic, events, ferry schedules (still uses the known ferry travel time). Optimized routes now disable the "Time Dependency" routing option.

**Comment by cmhodgson** [comment]
Confirmed in Delivery.
