### ISSUE TITLE
Improve turn-restrictions of MOT roads and truck routes on the Greater Vancouver Major Road Network

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#120]
Use turn-restriction editor. Making these improvements will allow us to turn on route planner turn-restrictions by default which will make generated routes much more realistic on the roads most-travelled on.

Note that the turn-restriction editor edits a turn-restriction file that is used by Routable BC Maker to generate a routable network file that will be loaded into Route Planner NG on bootup. ITN will be able to take advantage of these improved turn-restrictions when appropriate changes are made to the ITN data model and the ITN editor.

**Comment by BK01** [comment]
Continuing with MRN and HWY on Vancouver Island and lower mainland
