### ISSUE TITLE
Identify key turn-restrictions for review

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#124]
Identify key intersections for review and tag them in the database with a priority flag.  Likely need a new table with status field and row for every target intersection.  May also want a category/user division so that each operator can work independently on different intersection subsets.

**Comment by gleeming** [comment]
18804 intersections have been identified in the February ITN inputs for targeted review and recorded in the database.  These have been assigned a category name (e.g. Hwy 1, MRN1) and given a priority.
- priority 1: All highway corridors that pass through the lower mainland, from end to end.  Each has its own category.
- priority 2: Major Road Network (non-highway) nodes in the lower mainland.  Split into 4 distinct areas.
- priority 3: All other highways in the province, each with its own category.

If the study gets extended in the future, we can add additional intersections and categories to the database table that will then show up in the UI.

**Comment by mraross** [comment]
Verified
