### ISSUE TITLE
Enhance admin app and router configuration database to support configuration of all new features in Route Planner

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#127]
Move all suitable control parameters and variables from the code into Cassandra and test that the admin UI works with them

**Comment by cmhodgson** [comment]
Added a parameter named defaultDisableOptions which works the same as the "disable" parameter to the router API. It is a comma separated list of 2-letter codes which describe the routing functions/features to be disabled (all others are enabled). The codes are as follows:
TD = TIMEDEPENDENCY
TR = TURNRESTRICTIONS
TC = TURNCOSTS
EV = EVENTS
TF = TRAFFIC
SC = SCHEDULING (ferries)
Note that disabling Time Dependency disables time-dependent turn restrictions, events, traffic, and scheduling, as they all require the time feature. disabling Turn Restrictions will disable all turn restrictions, including time dependent, implied, and explicit (the distinction between implied and explicit is not currently made in the router code itself). The codes are case-insensitive.

**Comment by cmhodgson** [comment]
The new default disable Options parameter is confirmed working in delivery.
