### ISSUE TITLE
Add support for an excludeAreas user preference

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#13]
@mraross commented on [Fri Jan 19 2018](https://github.com/bcgov/api-specs/issues/287)

This allows a user to specify one or more areas of exclusion on a given route planning request.
Specify area of exclusion using an excludeAreas parameter which can take a comma-separated list of bboxes.

Take excludeAreas into account when computing best route.

**Comment by alixcote** [comment]
Closing. Will be implementing restrictions by road segment. Can re-open if clients request.
