### ISSUE TITLE
Prevent routing any direction across barricades

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#130]
Router currently ignores barricades. Can treat barricades in several ways:

1. Actually disconnecting the road-end from the intersection and placing a dead-end on the segment end
2. Adding a dead-end indicator to the road segment.
3. Generating the appropriate implicit turn-restrictions.

**Comment by cmhodgson** [comment]
The appropriate turn restrictions are now generated in the RoutableBC Maker.

**Comment by cmhodgson** [comment]
Confirmed working in delivery.
