### ISSUE TITLE
In turn-restriction editor, add support for intersection status display and control

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#132]
Add support for a intersection status field to allow users to understand what needs to be done, what is in progress, and what has been successfully or unsuccessfully done.

Ready - Intersection turn-restrictions are ready for review
UnderReview - review started but not finished
Validated - review completed successfully
UnValidated - review completed without being able to validate (usually due to lack of suitable source imagery or local knowledge) 

Need to update the turn-restriction schema in the database. 

Change the UI as follows:

1. When a user clicks on a turn-restriction, in the side-panel, display four buttons, one for each state. Highlight the button corresponding to the current state. 

Here is an example workflow:
1. Start up turn restriction editor. The side panel has no turn-restriction loaded and the intersection status buttons are greyed out.
2. turn on high priority intersections
3. Zoom to a ready, high priority intersection.
4. Click on a turn-restriction.  Details of that turn-restriction are loaded into the side panel. The intersection status buttons are greyed out and the unreviewed button is highlighted. Also, the View nearby photos (from openstreetcam) button is displayed.
5. Review the turn-restriction and all other turn restrictions in that intersection using local knowledge or using the view nearby photos function. 
6. Turn-restrictions look good so click on the Validated button.

**Comment by cmhodgson** [comment]
This workflow has been implemented and is live now in the turn restriction tool.

**Comment by mraross** [comment]
Verified
