### ISSUE TITLE
Add a button to zoom to and select the nearest intersection that is ready to be reviewed

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#134]
In the side-panel of the turn-restriction editor, add a button called NextIntersection that, when pressed,  zooms the map to the nearest intersection that is ready for review and has the same priority as the current intersection.  A defined turn-restriction of the new intersection is loaded into the side panel. If the new intersection has no defined turn-restrictions, an arbitrary, undefined turn-restriction is chosen.

**Comment by cmhodgson** [comment]
This is done in the live turn editor.

**Comment by mraross** [comment]
Verified
