### ISSUE TITLE
Optimized route slower than unoptimized route

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#137]
The optimized fastest route should be no slower than unoptimized fastest route since the unoptimized route is a valid route.

Fastest route; all advanced routing functions are turned off

3959 Olympic View Dr, Metchosin, BC
663 Radcliffe Lane, Oak Bay, BC
1566 Mileva Lane, Saanich, BC
2021 Haley Rae Pl, Langford, BC

Dev: http://office.refractions.net/~chodgson/gc/ols-demo/index.html?env=rri
Prod: https://bcgov.github.io/ols-devkit/ols-demo/index.html
Unoptimized: Route travels 58.04 km in 1 hour 7 minutes
Optimized: Route travels 67.297 km in 1 hour 15 minutes

Prod: https://bcgov.github.io/ols-devkit/ols-demo/index.html
Unoptimized: Route travels 57.752 km in 1 hours 7 minutes
Optimized:  Route travels 44.545 km in 51 minutes 36 seconds

**Comment by mraross** [comment]
Another example:

330 View Point Rd, Esquimalt, BC
1006 St. Charles St, Victoria, BC
3051 McAnally Rd, Saanich, BC
1938 West Park Lane, View Royal, BC

Dev - http://office.refractions.net/~chodgson/gc/ols-demo/index.html?env=rri
Unoptimized: Route travels 33.746 km in 43 minutes 14 seconds
    Optimized: Route travels 45.556 km in 56 minutes 14 seconds

Prod - https://bcgov.github.io/ols-devkit/ols-demo/index.html
Unoptimized: Route travels 33.49 km in 42 minutes 50 seconds
   Optimizied: Route travels 31.503 km in 40 minutes 24 seconds

**Comment by cmhodgson** [comment]
This bug was introduced when we moved to unidirectional edges and made changes to the shortest path algorithm details to support there now being 1 or 2 edges where there was only 1 possibly bidirectional edge previously. I have this fixed locally.

**Comment by cmhodgson** [comment]
Confirmed fixed in Delivery.

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in test
