### ISSUE TITLE
In functional router, take ferry schedules into account when computing best route

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#14]
@mraross commented on [Wed Nov 16 2016](https://github.com/bcgov/api-specs/issues/111)

Will need to load latest ferry schedules and require client to provide a  start date/time. Real-time schedule changes/delays are out of scope. 

We expect the ferry schedule will be available in _General Transit Feed Service_ (GTFS) format.  For details, see https://developers.google.com/transit/

---

@cmhodgson commented on [Wed Nov 16 2016](https://github.com/bcgov/api-specs/issues/111#issuecomment-261084603)

Some initial questions:
- how do we get the ferry schedule and how often does it update, and by what mechanism?
- does graphhopper support time-of-day based queries with dynamic costs such as this?

---

@mraross commented on [Wed Nov 16 2016](https://github.com/bcgov/api-specs/issues/111#issuecomment-261108591)

Don't know where or how. Could break estimate into two parts:
1.  Ferry schedule data prep (largely unknown effort)
2.  Using ferry schedule in route planning (largely known effort)

There are also two levels of ferry scheduling:
1. Static- based on seasonally published schedules
2.  Dynamic -based on notifications of sailing delays or cancellations

---

@cmhodgson commented on [Fri Nov 18 2016](https://github.com/bcgov/api-specs/issues/111#issuecomment-261681317)

It doesn't look like Graphhopper supports time-of-day based routing. I don't think it can be hacked on because we need to know the current time (based on the segments traversed so far) in order to determine the cost of a given segment. To be efficient, the routing algorithm needs to maintain a current time as it walks around the graph, otherwise we might have to recalculate it at every step.

**Comment by mraross** [comment]
Someone did a GFTS feed of all ferries accessible by transit.
https://github.com/GTFSForBCFerries/gtfs

**Comment by cmhodgson** [comment]
This is implemented using a GTFS feed we created, limited to vancouver island-mainland routes and some southern gulf island routes. In place on the dev server.
