### ISSUE TITLE
Add support for partial routes

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#140]
The route planner may not be able to find a valid route for a request that has multiple waypoints. In this case, return a valid, partial route that has the most waypoints.  This is useful in apps that allow users to interactively define a route using waypoints. They can simply redirect the route using waypoints until a valid, complete route is found.

For example, a user requests a time and road-restriction sensitive route from O to D through waypoints W1, W2, and W3.  The application makes a request to the route planner which couldn't find a complete valid route from O to D but finds a partial valid route from O to W2 which it returns to the app.  The app makes another request to the route planner for an unconstrained route from W2 to W3 and displays the invalid route and all violated restrictions along it. The user could then add or change their waypoints until a valid complete route is found.

Add an &isPartialRoute Boolean result parm which is True if returned route is is only partially complete (doesn't reach destination); false otherwise

**Comment by alixcote** [comment]
Close for now and re-evaluate if a use case comes up if this is the right approach.
