### ISSUE TITLE
in turn-restriction editor, colour intersection state buttons to match colours used in map

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#143]
Ready - Green
In Review - Blue
Validated - White
Not validated - Red

**Comment by cmhodgson** [comment]
Done. Please have a look. Previously the "blue" item was the selected item, once you color the buttons you need a different way to identify the selected item. I've bolded the font of the selected item and made the unselected items have an opacity of 0.6 which sort of "greys" them out.

**Comment by cmhodgson** [comment]
Done.

**Comment by mraross** [comment]
Verified
