### ISSUE TITLE
Partition best route by truck/non truck routes, ferries, and localities

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#162]
Routing applications need to style different parts of the best route in different ways (e.g., by truck/non-truck routes, by ferry/roads, by locality). By returning a list of sub-routes where each sub-route corresponds to a single sub-type (e.g., by ferry), a routing application can style each sub-route appropriately.

Partition roads of best route into truck route/ non-truck route portions.

Partition roads of best route into portions by locality. For TransLink truck routing, locality can serve as a proxy for road authority which isn't well-populated in ITN currently.

Identify ferry portions of best route.

A partition request parameter should allow a user to specify any or all of the above partitioning.

This feature is required by both TransLink and MOTI.

**Comment by mraross** [comment]
Don't need to divide best route. Best route is currently defined as an array of points so we can identify partitions of the route using array index ranges. Multiple types of partitionings can be supported (e.g., by locality, by vehicle/ferry, inside/outside Greater Vancouver) and they can even overlap.

**Comment by mraross** [comment]
TransLink identified a need to distinguish parts of the best route that are on the truck network from those that aren't. There should be at most, two parts off  the truck network, the part that gets onto the truck route from the origin point and the part that gets off of the truck network to the destination point.

**Comment by cmhodgson** [comment]
Here is how an example of how the partitioning will work. The points are from an actual arbitrary route but I've kept the route artificially short so as to make it easy to understand. I've also cut out a bunch of other bits that would be in the response that aren't relevant to the partitioning.

The route request would include a new parameter, "partition", which I've included in the response, but doesn't really need to be; in this case the value is "isFerry,isTruckRoute". I believe those are the current names we use internally for those attributes but the exact attribute names are not that important. The idea is the we could publish an arbitrary number of attributes that could be included in the list of attributes to partition on.

Here is what the routing response might look like:

{
  ...
  "points":[[-123.31591,48.42655],[-123.31175,48.42632]],
  "route":[
    [-123.31591,48.4265],
    [-123.31588,48.4265],
    [-123.31547,48.42649],
    [-123.31411,48.42647],
    [-123.31299,48.42644],
    [-123.31288,48.42643],
    [-123.31164,48.42641],
    [-123.31164,48.42632]
  ],
  "partition": "isFerry,isTruckRoute",
  "partitions": [
    {"index":0, "isFerry": false, "isTruckRoute": false},
    {"index":2, "isFerry": false, "isTruckRoute": true},
    {"index":4, "isFerry": true, "isTruckRoute": false},
    {"index":5, "isFerry": false, "isTruckRoute": true},
    {"index":6, "isFerry": false, "isTruckRoute": false}
  ]
}

The response includes the "partitions" attribute, which is an array of objects, each of which has an index (into the route coordinate array) and a value for each of the attributes requested in the partition parameter. I've chosen to make these boolean values, but there is no reason we couldn't have multi-valued attributed such as road class as well. The partitions array covers the entire route, so the first index is always zero, and the last partition is always from the last index to the end of the route. The order of this array is important and it would always be in the traversal order of the partitions of the route.

In this example, the partitions are:

- from index 0 to index 2, neither ferry nor truck route

- from index 2 to index 4, which is a truck route but not a ferry,

- from 4 to 5 is a ferry but not a truck route,

- from 5 to 6 is a truck route but not a ferry

- from 6 to 7 is neither for nor truck route

In a real example the indexes would typically be much further apart as there would be many coordinates in each partition, but I think this gets the point across.

**Comment by cmhodgson** [comment]
This is implemented now and deployed in Refractions test environment.

https://office.refractions.net/~chodgson/gc/ols-demo/?rt=rri

**Comment by cpspicer** [comment]
Chris - Please let us know when you've settled on any changes.  We can then dial in Ben to work on the application side calls / display properties.

**Comment by cmhodgson** [comment]
There are no changes planned or expected at this time, unless Brian has found any issues with his testing? Note that the truck route flag data on the Refractions test server has some holes until we reconcile the data against the latest ITN. But it should be workable for development.

**Comment by cpspicer** [comment]
Perfect - I've also seen the ticket where Ben can dial into your dev environment to shorten the development loop too.  We should be well positioned for the next client review.

**Comment by BK01** [comment]
Yes, this morning I was able to UAT and found that the response is ready to code against. As Chris said, there is still some data work to do but we can get started now.

**Comment by BK01** [comment]
UAT complete - Partitioning now distinguishes between truck routes, non-truck routes, ferry, locality.

**Example:**
isFerry: false,
isTruckRoute: false,
locality: "West Vancouver

**Comment by mraross** [comment]
Verified in dev
