### ISSUE TITLE
Route Planner v2.0 System Testing

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#168]
Use route planner testing framework to confirm system runs the same on Ministry infrastructure as it does on developer infrastructure.

**Comment by gleeming** [comment]
After running the full suite of custom and bulk tests forwards and backwards, there were no differences detected between development and deployment environments (apart from computation timings).  The data used in both infrastructures was sourced from:
- February ITN
- export of custom turn restrictions from the editor framework
- manually created GTFS mockup of some BC Ferries routes and sailing times
- generated (fake) traffic data from RoutableBC Maker
- custom modifications to downloaded MoT 511 events file

**Comment by cmhodgson** [comment]
System testing is complete in delivery. We have tested:
- RoutableBC Maker and associated data processing scripts
- Automated testing framework to test that 64 specific routes perform as previously determined to be correct, and that ~1600 generated routes perform consistently with previous runs
- Manual testing of OLS in Action app to confirm that various features work as expected
- OLS Admin App has been tested to show that it correctly affects the router's start-up configuration and can export and import config data 

We recommend moving to test. Note that the OLS in Action app will need to have the test server name updated to reflect the new test deployment in OpenShift.

**Comment by ll911** [comment]
would prefer add auto test to part of pipeline and turn auto migration to test.

**Comment by cmhodgson** [comment]
A complete automated test suite is a ways off and even if it succeeds, it is not always the case that you would want to migrate it to test (what if previous test version is still being tested?). This is going to remain a manual button for the immediate future.

**Comment by ll911** [comment]
just need a baseline of the test, not full test suite.
