### ISSUE TITLE
Update Route Planner Open API Specification to reflect v2.0 API

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#172]

**Comment by mraross** [comment]
Chris, please list changes to route planner api so I can update the open api spec

**Comment by cmhodgson** [comment]
new parameters:
- disable = comma separated list of codes: sc (ferry schedules), tf (traffic), ev (events), td (time dependency), tr (turn restrictions), tc (turn costs)
- departure= datetime with timezone in a format like this: 2019-04-08T14:48:00-07:00
- correctSide = boolean true/false

new truck-specific params:
followTruckRoute = boolean true/false
truckRouteMultiplier = numeric value
height = numeric value
width = numeric value
length = numeric value
weight = numeric value

**Comment by mraross** [comment]
Done

**Comment by mraross** [comment]
Need to add truck route parms
