### ISSUE TITLE
NFR - CICD with github actions

### ISSUE THREAD

**Issue by ll911** [bcgov/ols-router#184]
* push to dev trigger code scan + compile
* dev should be able to continue leverage maven life cycle for junit test or even sample data test.
* if success auto create pull request to master
* if pull to master approved auto trigger docker sidecar image build
* deploy docker side car image into public container registry (quay.io, docker.io or github package registry)
* send notification when push or pull or release happening
* auto trigger deployment into k8s/ocp cluster when new prod image released.

**Comment by alixcote** [comment]
New pipelines are in place now. Closing.
