### ISSUE TITLE
Add support for two types of waypoints:  stops and tweaks

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#186]
As a user, I want to be able to tweak the best route to reflect my local knowledge so that I get a best route that I feel more comfortable with. 

A stopover point is a location the user intends to stop at on their way to their destination. A tweak point is a location that serves to alter the best route found by the route planner to more accurately reflect the user’s local knowledge. A steiner point is a kind of tweak point.

In  optimalRoute resource request,  don't reorder tweak points; only stops

Enhance the route planner API to support stops from tweaks. This could take the form of a single, new parameter called tweakPoints which contains a comma-separated list of integers indicating position in points parameter. If there are usually more stops than tweaks in a given route, one could define a stopPoints parameter.

Past routing requests can be used to infer local knowledge and improve the routing algorithm (e.g., through some machine learning algorithm?). MOTI can use past routing requests to to inform the refinement of existing designated truck routes and corridors.

**Comment by cmhodgson** [comment]
In an optimal route request, the tweak points would have to thrown out; in any other request, they are treated the same as regular stops. This could be handled entirely by the UI. 

As far as using routing tweak points to infer local knowledge, that would require some level of permission. Again I think an MOTI-specific user interface could manage recording the tweak points outside of the router itself; with the eventual effect being to modify the cost values on which the router works. I don't think it would happen dynamically/automatically, but a machine learning algorithm could use such data to produce better cost values for the router to use, assuming there was enough of such data.

**Comment by mraross** [comment]
Of course, just don't give them to the route optimizer.

On the second point, not a problem. We just have a privacy disclaimer describing how exactly we will be using the tweak points. People could always just stick to stop points if they don't agree with the privacy policy but for those who want to provide local knowledge to improve the behavior of the route planner, tweaks are the feedback.

**Comment by mraross** [comment]
Not useful.
