### ISSUE TITLE
in route planner, add support for road elevation

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#19]
Road elevation is needed to more accurately compute distance and to determine turn restrictions for trucks that are based on slope.

@mraross commented on [Tue Nov 15 2016](https://github.com/bcgov/api-specs/issues/100)

This requires the ability to load road segments that have a third, Z coordinate for elevation and taking elevation into account when computing distance along a road segment.

This depends on the availability of BC Digital Road Atlas road segment data containing Z coordinates.

---

@cmhodgson commented on [Wed Nov 16 2016](https://github.com/bcgov/api-specs/issues/100#issuecomment-261091461)

We need more information about how we would get this data, what it is, and what would we do with it?

---

@mraross commented on [Wed Nov 16 2016](https://github.com/bcgov/api-specs/issues/100#issuecomment-261098861)

Estimate the effort for loading elevation data into graph hopper from a elevation data file that graph hopper supports. Estimate the effort of transforming the elevation data into a form required by Graph hopper. 

Elevation is currently accessible from the following WFS:
https://devoas1.apps.th.gov.bc.ca/ogs-geoV06/plg/ows?service=WFS&version=1.0.0&request=Getcapabilities

This is probably adequate for a pilot in a small area but we will need a more efficient format for production (e.g., file download in CSV format).

---

@cmhodgson commented on [Thu Nov 17 2016](https://github.com/bcgov/api-specs/issues/100#issuecomment-261420350)

The Graphhopper routing algorithm supports 3-d points on the graph linework, which we load from the GeoJSON file that comes out of the geocoder processing, from ITN. We don't even need graphhopper to do anything, we would just calculate the weight of the segments based on the 3-d length rather than the 2-d length, assuming this is the goal of this ticket? We could also add a maximum grade restriction, by calculating and tagging every segment with the maximum grade?

In order to get the z-values onto the ITN we would need to conflate the MoT segments with the ITN, likely at every monthly data processing, which might be possible with FME, but might require a more complicated process. If the matching segments have different vertices, how would we distribute the Z-values along the matched segment, being careful not to affect the calculated grade? I've not yet seen a solution to this sort problem that is entirely automated.

A more realistic approach would be to calculate the 3-d distance on the MoT segments, and also potentially the maximum grade, and then add that information to the ITN road network, based on the ITN IDs - this makes the assumption that we have ITN IDs available in the MoT data, or some other way to easily match up the linestrings between ITN and MoT.

---

@mraross commented on [Thu Dec 01 2016](https://github.com/bcgov/api-specs/issues/100#issuecomment-264276370)

I like the realistic approach of computing 2.5D distance and maximum grade on road segments using MoT roads and possibly TRIM. This does sound like something GeoBC should be doing though.

---

@cmhodgson commented on [Fri Apr 28 2017](https://github.com/bcgov/api-specs/issues/100#issuecomment-298081274)

Have we resolved my comment from Nov 17? Do we know how we would get the z-values onto the linestrings? 

---

@mraross commented on [Fri Apr 28 2017](https://github.com/bcgov/api-specs/issues/100#issuecomment-298130079)

GeoBC said they will be adding Z to road points by end of fiscal. They will be building a new DEM to drape the road geometry over. Does graphhopper handle (x,y,z) points?

---

@cmhodgson commented on [Mon May 01 2017](https://github.com/bcgov/api-specs/issues/100#issuecomment-298469309)

Yes. as I said earlier in the comments, graphhopper does support 3-d coordinates, we just have to tell it to do 3-d distance calcs. This should be fairly trivial, will just require some testing.

**Comment by alixcote** [comment]
We don't have the data right now and can use local distortion fields if needed.
