### ISSUE TITLE
Add support for Barnston Island ferry

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#191]
Barnston Island is an inland ferry that operates on-demand within given hours of operation. See:

https://www2.gov.bc.ca/gov/content/transportation/passenger-travel/water-travel/inland-ferries/barnston-island-ferry

This ferry is needed in support of the TransLink Commercial Vehicle Route Planner (CVRP) version 1.0

**Comment by cmhodgson** [comment]
It should be noted that the ferry schedules are currently manually created one-time and were intended for demonstration purposes only. There is no process in place to update the schedule seasonally, yearly, or to include special holiday schedules.

We currently do not have support for limiting on-demand ferries to particular hours of operation. This could be added without much difficulty; I expect we will need to support hours of operation by day-of-week. The complexity of this requirement goes up another notch if it needs to support seasonal changes or holiday schedules. 

While the hours of operation could be managed using an approach similar to the GTFS schedules, I do not believe that on-demand trips are within the scope of GTFS, meaning that if this information was to be communicated in the future, a new format, or an extension of GTFS, would be required.

**Comment by gleeming** [comment]
GTFS does support irregularities in route scheduling, but we have not looked into implementing this yet (e.g. known holiday exceptions).  Also for the current demonstration routes, special crossings such as dangerous goods sailings have been excluded.  These may in fact be useful for Translink, but we'd have to extend our model to support such additional parameters.

Also, small inland ferries may have access, weight and size limits that would make them unsuitable for large trucks.  For example Big Bar Reaction Ferry has a capacity for 2 vehicles and has a wooden deck & ramp from a sandy road approach.  Like Barston Island Ferry, it has service hours as well as a note that it won't operate when water is low or icy.

**Comment by mraross** [comment]
Could on-demand ferries could be handled as road events?

**Comment by gleeming** [comment]
The router has Barnston Island Ferry as a non-scheduled route.  There is also a Translink truck notice associated with it.  As Chris notes, there is currently no logic implemented to limit hours of operation on unscheduled routes.

**Comment by mraross** [comment]
Works.
