### ISSUE TITLE
Update Bowen Island ferry schedule

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#192]
Bowen Island is a regularly scheduled ferry operated by BC Ferries. See:

http://www.bcferries.com/schedules/mainland/biva-current?scheduleSelect=sch05141504.html

Bowen Island is needed for TransLink commercial vehicle route planner application

**Comment by gleeming** [comment]
A static RoutableBC input in GTFS format has been created based on the current winter Bowen Island sailing timings posted on the BC Ferries website.  The router does not currently handle exception days (e.g. dangerous cargo and holidays) so it just models a regular schedule of daily sailing times.
This schedule addition was provided last month to DataBC as part of the October set of RoutableBC inputs.

**Comment by mraross** [comment]
Reviewed
