### ISSUE TITLE
Sometimes the directions are missing the distance

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/ols-router#198]
**Describe the bug**
Sometimes the `directions` structure contains entries that are missing a distance, for example:
```
      {
            "type": "CONTINUE",
            "text": "Continue onto Patricia Bay Hwy for  km (18 minutes 11 seconds)",
            "point": [
                -123.37772,
                48.4594
            ]
        }
```
(No distance after `Patricia Bay Hwy`)

**To Reproduce**
```
curl 'https://router.api.gov.bc.ca/directions.json?criteria=shortest&distanceUnits=km&outputSRS=4326&points=-123.3851129%2C48.4433601%2C-123.4670671%2C48.7602305' -H 'authority: router.api.gov.bc.ca' -H 'accept: application/json, text/javascript, */*; q=0.01' -H 'apikey: <key>' 
```
Look at 12th entry in `directions` structure in result

**Expected behavior**
A distance in for this direction.

**Comment by cmhodgson** [comment]
This seems to happen on long legs of the router that are at least 10km or more, I suspect my math in the conversion isn't working quite right, or I'm looking in the wrong field. (note to self for when I get fixing this)

**Comment by cmhodgson** [comment]
This is fixed locally. Error in the rounding/formatting logic.

**Comment by mraross** [comment]
Verified in dev
