### ISSUE TITLE
Add "enable" parameter as an alternative to disable

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#200]
The operation and name of the "disable" parameter was chosen because it was expected that the list of functions to disable would be shorter than the list of functions to enable; however, if new (potentially experimental) functions are added to the router in the future, clients using a hard-coded list of disable features would have the features enabled unintentionally, which could have undesirable side effects. Perhaps the disable parameter should even be deprecated due to this.

If we allow for either or both parameters, we need to consider the precedence; to disables override enables, or vice versa? My feeling right now is that we should actually deprecate disable altogether, and ignore it if an enable is provided; only if a disable is provided and no enable should we maintain the current behaviour.

**Comment by mraross** [comment]
Need to add ldf (local distortion field) and gdf (global distortion field) to the list of options that can be enabled

**Comment by cmhodgson** [comment]
This is done and deployed. ldf/gdf will be added with their respective tickets.

**Comment by mraross** [comment]
Verified in test
