### ISSUE TITLE
Add support for vehicle specific restrictions in editor app

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-router#203]
Enhance the Turn Restriction Editor to allow users to:
1. Display new vehicle-specific turn restriction data
2. Edit and/or flag vehicle-specific turn restrictions

Vehicle types:
> Start with 'truck' as a MVP

Continue to record edited restriction data to a separate location until ITN model is updated

**Comment by cmhodgson** [comment]
This may need to be done for 2.1, at least the viewing portion, if we are going to support vehicle-specific turn restrictions for CVRP.

**Comment by cmhodgson** [comment]
Done.

**Comment by BK01** [comment]
Tested in rri with All/Car/Truck.
