### ISSUE TITLE
Add support for notification restrictions

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-router#204]
Although notification restrictions will not impact the route calculation itself, users of the BC Route Planner need to be aware. For example, a road segment may be restricted for a specific type of vehicle during certain hours, or under certain conditions.

To accomplish this: 
- The BC Route Planner must know which segment IDs correspond to each notification. 
- Define a file structure and select a format to hold this information.
- Read into the BC Route Planner on start-up. 

Notes:
- Only output from the _truck_ resource will contain notifications in the returned response.
- The notifications do not affect routing decisions.

**Comment by mraross** [comment]
Ben and Chris got together and hammered out this proposal for truck notifications that are tied to road segments:

The router currently has a field in the response called notifications. There is also an optional notifications field within each direction in the driving directions. Here is the json of the notifications field:

` [
    {
        type: "<type-name>"
        message: "<message-text>"
    }
    {
        type: "<type-name>"
        message: "<message-text>"
    }
]` 

What we are proposing is that, when the /truck/directions resource is accessed, the response would include additional notifications, determined by segments of the route which have notifications associated with them. We would only return a unique list of such notifications, even if multiple segments of the route have the same notification associated with them.

Attached is the unique set of truck notifications, note that they are grouped into 3 types: border, restriction, and advisory. The existing notification types in the router are: Oversize, EventWait, FerryWait - and the waits are currently only used within the directions. 
The border, restriction, advisory types are specific to Translink and trucks; we propose the following notification types for the border, restriction, and advisory notification types that are specific to TransLink:

- TruckBorder
- TruckRestriction
- TruckAdvisory

**Comment by cmhodgson** [comment]
This is implemented in the router now and deployed to the rri server.

**Comment by mraross** [comment]
verified in dev
