### ISSUE TITLE
betweenPairs - "routeFound":true when not found

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-router#206]
When submitting a betweenPairs request that includes a known address in an isolated portion of the road network (on a small island) a route may not be found.

In such cases, when using betweenPairs the response includes the correct -1 values but with "routeFound":true.

**Example:**
The following site can be located by the Geocoder but is on an island road that is disconnected from Vancouver Island and does not have a ferry.

**Address:** 100 Okime Island, Kyuquot, BC

**Response extract:** 
https://router.api.gov.bc.ca/distance/betweenPairs.json

      "distance": "-0.001",
      "time": -1,
      "timeText": "-1 seconds",
      "routeFound": true

**Comment by mraross** [comment]
Verified in delivery using:
https://router-dev.pathfinder.gov.bc.ca/distance/betweenPairs.json?apikey=11dd756f680c47b5aef5093d95543738&fromPoints=-127.3660892%2C50.0278214&toPoints=-125.3180779%2C50.0598817&criteria=fastest

**Comment by mraross** [comment]
Verified in production

**Comment by mraross** [comment]
Verified in delivery using April 2020 data.

**Comment by mraross** [comment]
Verified in delivery using May 2020 data.

**Comment by alixcote** [comment]
This is resolved.
