### ISSUE TITLE
Truck/non-truck partitioning not correctly handling partitions that start at first and last turns

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#208]
In this [Example](https://user-images.githubusercontent.com/20274603/72838034-651c0800-3c44-11ea-8d08-0584bac1f9da.png), the line on blanshard from fort st to view st should be classified as a truck route, not a non-truck route.

**Comment by cmhodgson** [comment]
Off-by-one error in the partitioning code. Fixed now on the Refractions demo server.

**Comment by mraross** [comment]
Verified
