### ISSUE TITLE
Add support for new ITN local/express ferry classes

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#21]
@mraross commented on [Fri Mar 03 2017](https://github.com/bcgov/api-specs/issues/151)

---

@cmhodgson commented on [Fri Apr 21 2017](https://github.com/bcgov/api-specs/issues/151#issuecomment-296262221)

Support was already added for FERRY_PASSENGER. 

---

@mraross commented on [Fri Apr 21 2017](https://github.com/bcgov/api-specs/issues/151#issuecomment-296279258)

At MOTI's request, BC Ferries is going to create new ferry classes this fiscal to distinguish local from express so that routers won't jump from one the other at common docks.

---

@cmhodgson commented on [Fri Apr 21 2017](https://github.com/bcgov/api-specs/issues/151#issuecomment-296311858)

Why would we not change ferries at a dock? What does "support" mean in terms of the geocoder? Just add them to the accepted road classes? Ferries segments don't have addressing anyway, I think we just need to ignore them at some level.

---

@mraross commented on [Fri Apr 21 2017](https://github.com/bcgov/api-specs/issues/151#issuecomment-296313612)

I might not have the new typology right but from what I recall, OnRoute was having trouble routing with the current ferry classes and we would too if BC Ferries  didn't add new ferry classes

**Comment by alixcote** [comment]
Closing. Will be fully spec'd out in the future with new ferry data.
