### ISSUE TITLE
Unexpected Route

### ISSUE THREAD

**Issue by gk-tl** [bcgov/ols-router#210]
East-West route through New Westminster is not consistent with expectations. While the generated route is "valid" from a bylaw compliance perspective (depending on the time of day), a route via Front Street wold be more consistent with industry and municipal preferences. 

Route via Front Street avoids steep grades on McBride Blvd and Royal Ave (which is also a limited use truck route with a time restriction)

![image](https://user-images.githubusercontent.com/59627982/72945668-5e1ef380-3d31-11ea-9130-8ffb4fe206e9.png)

@al-tabb - please weigh in.

**Comment by mraross** [comment]
Nicole and I also agreed that by changing the beta app behaviour when you click on the map to simply picking up the coordinate location under the cursor and adding it as a waypoint to the route would allow you to define a route from and to anywhere on the road network including port terminals, highway shoulders, etc.

Currently in the beta app, when you click on the map, the app looks for the nearest civic address to the point, which, in many cases, can be quite far from cursor location.

**Comment by mraross** [comment]
As for the route planner not following Front St instead of Royal and McBride, what data is available to your old beta that allowed it to follow Front St?

**Comment by gk-tl** [comment]
TL BETA also generated the unexpected route via Royal Ave. However, the cost for a designated truck route with restrictions (i.e., Royal Ave) should be slightly higher than for a designated truck route without restrictions (i.e., Front Street).

**Comment by al-tabb** [comment]
I don’t believe there is currently an exception for Front St in the database.  However there could be a number of exceptions added that would either decrease the cost of Front St segments relative to Royal and McBride or increase the cost of Royal and McBride segments relative to Front St.

All of the exceptions are captured in the table ‘exceptions’ in the PostGIS database.  There is a python script that I believe I passed on earlier that calculates the ‘default cost’ of all segments based on their truck route status and road type.  The ‘final costs’ of any exception segments are calculated from the information captured in the ‘exceptions’ table.  Many of them simply reverse the cost (multiply by -1) but some do a relative calculation to favour them over other segments.  The Front St example would fall into the latter category.

**Comment by gk-tl** [comment]
> All of the exceptions are captured in the table ‘exceptions’ in the PostGIS database. There is a python script that I believe I passed on earlier that calculates the ‘default cost’ of all segments based on their truck route status and road type. The ‘final costs’ of any exception segments are calculated from the information captured in the ‘exceptions’ table.

During a follow-up convention re. this ticket, @al-tabb  aptly pointed out exceptions are needed given there will always be edge cases where we need to calculate costs differently from our general classification scheme (i.e. opening up a small number of private, restricted, etc. roads for truck travel). 

An exceptions table would address the Royal Ave vs Front Street route and any other "fine tuning" needed to generate routes consistent with user expectations that don't fit the general classification scheme.

Happy to discuss further.

**Comment by gk-tl** [comment]
A somewhat stylized example of an existing "exception" in the TL BETA:

Maple Ridge - Lougheed Highway between Kanaka Way and 222 Street is an exception in the TL BETA. The cost is set higher relative to Haney Bypass so that the Bypass is more likely to be selected as the potential route,, particularly when the truck is not making any deliveries in Maple Ridge. 

Similar to the case of Royal Ave vs Front Street, while Lougheed and the Bypass are valid routes from a "compliance" perspective, funneling trucks to the Bypass is more consistent with prevailing land-use along the segment of Lougheed Hwy between Kanaka Way and 222 Street, which is effectively the town centre for Maple Ridge (and hence a less appealing option for trucks than the Bypass).

![image](https://user-images.githubusercontent.com/59627982/73107112-ec21e800-3eb1-11ea-935a-c45ce68747af.png)

![image](https://user-images.githubusercontent.com/59627982/73109531-3a39ea00-3eb8-11ea-8102-8bb0d1a7803c.png)

**Comment by qqnluaq** [comment]
Found another weird route:
![image](https://user-images.githubusercontent.com/20274603/73214742-9fcfe580-4107-11ea-93cc-e0d6660229c3.png)

Going south on Blanshard past Belleville isn't allowed for any vehicle.

**Comment by mraross** [comment]
The route planner in the demo app is not routing south below Belleville

![image](https://user-images.githubusercontent.com/11318574/73216258-81b7b480-410a-11ea-833b-e2a32267edc0.png)

**Comment by cmhodgson** [comment]
Ben can you send me the URL you are hitting to get that result?
I wonder if turn restrictions are disabled?

**Comment by cmhodgson** [comment]
I have some untested code in place to support moving to an "enable"-based routing option control from the current "disable" based approach - this is causing the default enabled options to be inverted, which means that Turn restrictions are defaulted to off. I have the fix in my local code, I'm in the middle of some other changes so I'm not going to deploy this fix immediately, but it will be in place by the end of the week at latest.

**Comment by gk-tl** [comment]
Hello everyone. I'm wondering whether it is necessary to test the router in Victoria (at this point) given that we only have municipal truck route data for the Lower Mainland. Some of the issues above could be the result of incomplete truck route info for Victoria.

**Comment by cmhodgson** [comment]
Local knowledge plays an important part in validating route results, and we may not all have good local knowledge of the Lower mainland truck routes. While the Victoria-area example may not be a good direct test of the truck routing in the lower mainland, it did find an important global bug which would also manifest all over BC. The fix for it, however trivial, is accounted for under the router maintenance contract, not on Translink's dime.

**Comment by mraross** [comment]
To add to Chris's comment, the router must route right across BC since that is still in scope for the TransLink app.

**Comment by gk-tl** [comment]
Thank you for clarifying.

**Comment by mraross** [comment]
East-west route through New Westminster looking better; now taking Front St.

![image](https://user-images.githubusercontent.com/11318574/76824901-be805d80-67d5-11ea-8bd6-5c99c684067a.png)

**Comment by gk-tl** [comment]
Looks good. Thanks Michael.

**Comment by mraross** [comment]
Verified in delivery
