### ISSUE TITLE
Router Response should include Enabled Route Options

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#211]
We should include a field with the list of the enabled route options (as a mirror to the request) - this is useful when looking at a route result without having the request in hand, and improves visibility of the route options, also makes it easy to check that the expected options are being used for a request.

Current Route options:
	TIMEDEPENDENCY("td"),
	TURNRESTRICTIONS("tr"),
	CROSSINGCOSTS("xc"),
	EVENTS("ev"), 
	TRAFFIC("tf"),
	SCHEDULING("sc"),
        LOCAL DISTORTION FIELD ("ldf")
        GLOBAL DISTORTION FIELD ("gdf")

**Comment by cmhodgson** [comment]
This is implemented now in on RRI dev server

**Comment by mraross** [comment]
Verified in test
