### ISSUE TITLE
Support one-way Weight Restrictions

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#212]
Use the weight restriction on the end of the segment the vehicle enters from to prevent routing overweight vehicles on streets in one direction (eg. downhill on steep streets in west Van). This is to support some specific by-laws for CVRP.

**Comment by cmhodgson** [comment]
This is lice now on RRI dev server

**Comment by mraross** [comment]
Verified in test with:
49.33606,-123.15370
49.33180,-123.15743
and 30000 GVW
