### ISSUE TITLE
Add support for global road distortion fields

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#216]
Route planner should take isTruck, isTruckRoute and ITN road class into account when computing road segment friction (slowing) factor.

isTruck is a flag which if true, means the vehicle being routed is a commercial vehicle; false otherwise

For the sake of this example, assume ITN has an isTruckRoute flag and only the following road classes: 

   {highway,freeway,arterial,residential,private}

The truckRouteMultiplier function needs to remember and use a table of friction factors that lengthen road segment travel time. Here is an example table:<br><br>

| isTruckRoute  | roadClass | frictionFactor|
| --------------- | --------- | ------------|
 false | highway | 1|
 false | freeway| 2|
 false|arterial| 5|
 false|residential|10|
 false|private|10000|
 true|highway|1|
 true| freeway |2|
 true|arterial|3|
 true|residential|6|
 true|private |16|

According to the table above, a highway has no friction, a freeway has a wee bit of friction; arterial and residential roads have some friction but less if they are designated truck routes; and a private road has a lot of friction unless it is a truck route.

if isTruck=false then  isTruckRoute should be set to false when looking up friction factors.

TransLink has  examples of designated truck routes on private roads (e.g., true,private) including CenTerm, VanTerm and DeltaPort.

**Comment by gleeming** [comment]
This table would be configurable in the Router admin app, and also override-able by HTTP request parameters.

**Comment by mraross** [comment]
We can reuse the truckRouteMultiplier parameter as follows:

1. If a single value is provided in a truck resource request, that value is used instead of the table of weights.
2. If a comma-separated list of values is provided, that list is used instead of the default table of weights.

**Comment by mraross** [comment]
Extend the concept of distortion field to apply to standard vehicles as well to keep them off residential streets during their daily commute. Alternately, the concept of keeping through-traffic on major roads and off residential roads applies to both trucks and commuter vehicles.

**Comment by mraross** [comment]
Globa distortion fields (ldf) should be included as an option in the enable parameter.

**Comment by cmhodgson** [comment]
This is implemented and deployed on Refractions dev server. Still working on the UI.

**Comment by cmhodgson** [comment]
Currently the GDF is based on the vehicle type and road class; the original intent was to base the GDF on the RoadClass and truckRoute status of the segment, and only apply to truck vehicles. I will change the implementation to work the originally intended way.

**Comment by cmhodgson** [comment]
I think the code excerpt below is the clearest way to express the multiplier logic:

```
private double getMultiplier(int edgeId) {

		double multiplier = 1;
		if(params.isFollowTruckRoute() && !graph.isTruckRoute(edgeId)) {
			multiplier *= params.getTruckRouteMultiplier();
		}
		if(params.isEnabled(RouteOption.LOCAL_DISTORTION_FIELD)) {
			multiplier *= graph.getLocalDistortion(edgeId, params.getVehicleType());
		}
		if(params.isEnabled(RouteOption.GLOBAL_DISTORTION_FIELD) && params.getVehicleType() == VehicleType.TRUCK) {
			multiplier *= params.getGlobalDistortionField().lookup(graph.getRoadClass(edgeId), graph.isTruckRoute(edgeId));
		}
		return multiplier;
	}
```

**Comment by cmhodgson** [comment]
This is live now on rri. I changed the wording of the config table headers slightly to reflect, but the tuning string is unaffected, as are the actual API parameters. The <roadClass>.truck now has a different meaning which applies to truck route segments.

**Comment by mraross** [comment]
Looking good. I noticed that the truck route multiplier is still having an important effect on best route. Is that good or bad?

**Comment by cmhodgson** [comment]
As shown in my code, the truck route multiplier is still in the equation, you can think of it as a pre-scaling factor on the truck route global distortion field, as it will affect the same same segments, regardless of roadClass.

**Comment by mraross** [comment]
Verified in test
