### ISSUE TITLE
Enhance turn costs for dynamic adjustability

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#218]
The previous turn costs model did not allow for changing turn costs per request. We propose:
- RouteableBC maker identifies a "TurnClass" value (left/center/right) for all possible turns, and stores this in a new turn_class.csv file
- Route Planner reads the turn classes on startup
- default values for the costs of each turn class (in seconds) are specified in the router admin app
- alternative values for the costs of each turn class can be specified in the request, by extending the xingCosts parameter to accept a left and right turn cost value in addition to the current XingCosts value
- the router determines the costs of turns based on the values specified in the request (falling back on the default values if none are given in the request) based on looking up the turnClass using the ids of the street segments involved

Note that this will re-introduce a minor issue with the "shortest" route sometimes being faster than the calculated "fastest" route, but we have determined that this issue is minor in comparison to the importance including turn costs in the calculation of optimal routes.

**Comment by mraross** [comment]
Turn costs (tc) should be included as an option in the enable parameter.

**Comment by mraross** [comment]
Turn costs should include separate costs for both commercial and non-commercial vehicles. In other words, turn costs should be a function of both turn-type (e.g., left, right) and isTruck where isTruck is a boolean that is true if vehicle being routed is a commercial vehicle; false otherwise

**Comment by mraross** [comment]
In Routable BC Maker, in addition to computing turn-class, compute and store inner turn angle. This angle could be used to implement dynamic turn-restrictions such as no left-turn for trucks if inner turn angle < 30 degrees and truck length > X metres.

**Comment by cmhodgson** [comment]
We can calculate turn angles on the fly relatively inexpensively and already do support this use case.

**Comment by cmhodgson** [comment]
This is implemented and in both refractions dev and the gov delivery/dev environment.

**Comment by mraross** [comment]
Verified in test
