### ISSUE TITLE
Turn restrictions are no longer being generated to prevent flow across segment ends with barricade impactors

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-router#220]
Restore functionality we previously had to generate turn restrictions across segment ends with barricade impactors.  This may have occurred with the XingCost changes were introduced in ticket #213.

**Comment by cmhodgson** [comment]
This is fixed now in the routable BC maker and the data is up on the RRI dev server

**Comment by mraross** [comment]
Verified in test
Caledonia and Vancouver in Victoria
48.42995,-123.35571
48.43234,-123.35543
