### ISSUE TITLE
Odd partition signatures

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#224]
Golden Ears Offramp
from 49.18759,-122.66536
    to 49.17278,-122.66922

Data fixed:

![image](https://user-images.githubusercontent.com/11318574/76916703-8123da80-687e-11ea-9805-db682f11b0c6.png)

Golden Ears Onramp
from 49.17744,-122.66313
    to 49.19029,-122.66304

data fixed:

![image](https://user-images.githubusercontent.com/11318574/76916786-c811d000-687e-11ea-8f11-92ba0af69309.png)

**Comment by mraross** [comment]
Golden Ears Offramp
from 49.18759,-122.66536
    to 49.17278,-122.66922

**Comment by mraross** [comment]
Golden Ears Onramp
from 49.17744,-122.66313
to 49.19029,-122.66304

Confirmed by Al Tabbernor, TransLink

**Comment by mraross** [comment]
turn from St Johns St to Clarke Rd, Port Moody

from 2010 St. Johns St, Port Moody, BC
    to  49.27542,-122.86976

**Comment by mraross** [comment]
Agree on need for truck route flag.

**Comment by mraross** [comment]
from 4085 Kincaid St, Burnaby, BC
   to   49.26495,-123.01752

Illegal U-Turn at Boundary and Lougheed Highway

![image](https://user-images.githubusercontent.com/11318574/75296145-44197a80-57e1-11ea-9b65-a205bb468592.png)

**Comment by gleeming** [comment]
You need to enable turn restrictions.  There are 4 no-u-turn restrictions at that intersection

**Comment by mraross** [comment]
Doh!

**Comment by mraross** [comment]
4047 Kamloops St, Vancouver, BC
3372 Monmouth Ave, Vancouver, BC

![image](https://user-images.githubusercontent.com/11318574/75296789-0ddcfa80-57e3-11ea-86c2-26aae9317153.png)

**Comment by mraross** [comment]
675 Pacific St, Vancouver, BC
105 N Commercial Dr, Vancouver, BC

![image](https://user-images.githubusercontent.com/11318574/75297239-2d285780-57e4-11ea-8328-1c356880d9f4.png)

**Comment by al-tabb** [comment]
@mraross The dotted red segment should be classified as a truck route.  Good catch, looks like this is missing in our BETA as well.

**Comment by mraross** [comment]
Thanks Al.

**Comment by mraross** [comment]
910 Handsworth Rd, District of North Vancouver, BC
103 29th St, West Vancouver, BC

![image](https://user-images.githubusercontent.com/11318574/75300641-674a2700-57ed-11ea-904f-b609d0439118.png)

**Comment by mraross** [comment]
Taylor Way onramp should be a truck route
![image](https://user-images.githubusercontent.com/11318574/75300804-e17aab80-57ed-11ea-8255-4736eb363e85.png)

**Comment by mraross** [comment]
@al-tabb Please review fixes above. Taylor Way on/off ramps still not designated truck routes.

**Comment by gleeming** [comment]
I have now included these cases as part of a ticket batch for GeoBC, hopefully to be updating in the April ITN release.  In our initial reconciliation of truck routes from Translink we deliberately did not extend designations to highway routes within the MVRD.  The Lion's Gate Bridge, for example, is explicitly not a truck route despite being part of route 1A and 99.

If there is an official Translink or MoTI policy for associating truck routes with highway ramps, it would be useful for all to understand how this attribute should be managed and updated in the ITN.

**Comment by al-tabb** [comment]
After some discussion with @gk-tl we came up with a (hopefully) simple rule.  In the case of freeway or highway on/off ramps, if the ramp serves as a connection between two designated truck routes then we should classify that on/off ramp as a truck route.  If a freeway or highway on/off ramp connects a truck route to a non-truck route (or vise versa) we should classify that on/off ramp as a non-truck route.

**Comment by mraross** [comment]
Taylor ramp issues moved to issue
All other issues verified
