### ISSUE TITLE
Missing truck route at bridle falls

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#225]
@mraross commented on [Tue Feb 25 2020](https://github.com/bcgov/ols-geocoder/issues/71)

55270 Chilliwack Bench FSR, Chilliwack River Valley, BC
6155 Rockwell Dr, Agassiz, BC

Bridal Falls Offramp Rd EastBound not classified as truck route sending trucks the long way around to get to Agassiz

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/f8dd5467-5a1e-4af5-a575-6e9a55f0393e)

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/537f57e3-932f-45e7-b9ac-027a8e300355)

---

@gleeming commented on [Tue Feb 25 2020](https://github.com/bcgov/ols-geocoder/issues/71#issuecomment-591191535)

This should be moved to router issues.

There are lots of "missing" cases like this at highway on/offramps.  We have not been updating them because I don't know what the local truck bylaws state for these cases. We have also been concerned that there may be some ramps that are deliberately excluded from the truck layer.  These could be cases with steep/tight curves or have banks that could be problematic for trucks with tall loads.

**Comment by gleeming** [comment]
This one is also well outside of Translink's domain, so this area has only been assigned truck routes based on the ITN highway route numbers.

**Comment by mraross** [comment]
True, not urgent.

**Comment by gleeming** [comment]
Right, but it comes down to who is responsible for authoritatively determining what should and should not be a truck route.  In cases like this it feels like we are just arbitrarily wanting to make the change because the route would seem to flow better.

If MoT or Translink had a set of rules around onramps/offramps then you could use that as a guide and report such issues to GeoBC (or have us do it on your behalf) since they are now responsible for managing that ITN attribute.  Translink made it very clear that in most cases truck routes should not be extended/tweaked/removed because bylaws can be very specific about their exact extents.

**Comment by mraross** [comment]
Ok, I will have a chat with MoTI about highway ramps

**Comment by gleeming** [comment]
The long run pathing isn't actually related to truck routes at all.  There is either a data oddity where Hwy 9 crosses the Trans-Canada Hwy or a router bug.

This can be seen by changing the route endpoint so it is located on the Hwy 9 Offramp on the southside cloverleaf.  The path starts out valid.  Keep moving it further around clockwise and then onto the northbound Hwy 9 segments that cross over the TCH.  For some reason the route is not able to pass overtop of the westbound lane without being diverted out and back.

**Comment by gleeming** [comment]
It was a data issue in Feb ITN related to incorrectly assigned overpass traffic impactors.  I had ticketed it in JIRA last month, and it looks like the attributes were fix in the March release.

**Comment by mraross** [comment]
Excellent news. Thanks for checking.

**Comment by mraross** [comment]
overpass traffic impactors have been fixed. Route now takes offramp and proceeds on to Aggasiz. Truck route designation to be dealt with in a separate issue.
