### ISSUE TITLE
Define benchmark routes in Metro Vancouver area.

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#229]
TransLink to provide benchmark routes for use in QA of latest Route Planner.

**Comment by mraross** [comment]
From Al at TransLink:

https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3546814899&startLong=-122.7758149484&endLat=49.2259251979&endLong=-122.9642991403&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.2463174483&startLong=-123.193896232&endLat=49.2462053862&endLong=-123.1733826974&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3799145203&startLong=-123.3394650796&endLat=49.0951154457&endLong=-122.4770383218&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.2864312418&startLong=-123.1344584802&endLat=49.1509407067&endLong=-122.8236226419&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.1931701306&startLong=-122.7068929055&endLat=49.0876069061&endLong=-123.0124501565&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.2467897032&startLong=-122.7268056253&endLat=49.1731901597&endLong=-122.4262265542&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.158822935&startLong=-123.190291343&endLat=49.0126695795&endLong=-123.0811147073&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.158822935&startLong=-123.190291343&endLat=49.0241275506&endLong=-123.1566457131&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.2489014571&startLong=-123.0176429131&endLat=49.224468966&endLong=-123.030410228&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3417985382&startLong=-123.077531276&endLat=49.15309085&endLong=-122.822957454&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=9000&truckHeight=4.15&startLat=49.2241932865&startLong=-122.9177493212&endLat=49.179533492&endLong=-122.8568309901&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3954699639&startLong=-123.2513732074&endLat=49.0910025574&endLong=-122.4664515612&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3954699639&startLong=-123.2513732074&endLat=49.0649350225&endLong=-122.5180787204&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.2540144978&startLong=-123.1272857674&endLat=49.0334687845&endLong=-123.0696075448&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.15&startLat=49.3441826766&startLong=-123.1782101367&endLat=49.3287023459&endLong=-123.1623494608&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=9000&truckHeight=4.15&startLat=49.3441826766&startLong=-123.1782101367&endLat=49.3287023459&endLong=-123.1623494608&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=8000&truckHeight=4.15&startLat=49.3441826766&startLong=-123.1782101367&endLat=49.3403321869&endLong=-123.1707428668&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.15&startLat=49.3441826766&startLong=-123.1782101367&endLat=49.3403321869&endLong=-123.1707428668&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.5&startLat=49.3417985382&startLong=-123.077531276&endLat=49.15309085&endLong=-122.822957454&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=5.25&startLat=49.3095108803&startLong=-123.0761365273&endLat=49.15309085&endLong=-122.822957454&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=64000&truckHeight=4.15&startLat=49.2241932865&startLong=-122.9177493212&endLat=49.179533492&endLong=-122.8568309901&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.5&startLat=49.3954699639&startLong=-123.2513732074&endLat=49.0649350225&endLong=-122.5180787204&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=4.5&startLat=49.3954699639&startLong=-123.2513732074&endLat=49.0649350225&endLong=-122.5180787204&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=18200&truckHeight=5.15&startLat=49.2540144978&startLong=-123.1272857674&endLat=49.0334687845&endLong=-123.0696075448&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.5&startLat=49.3761578346&startLong=-123.2666372035&endLat=49.1452219052&endLong=-122.7851270411&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.5&startLat=49.214450836&startLong=-122.6681398127&endLat=49.1774326821&endLong=-122.750708935&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.9&startLat=49.2355420143&startLong=-122.6344178464&endLat=49.1774326821&endLong=-122.750708935&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.3&startLat=49.2355420143&startLong=-122.6344178464&endLat=49.1774326821&endLong=-122.750708935&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=5.7&startLat=49.272055542&startLong=-123.2070587422&endLat=49.0781339491&endLong=-122.6937912251&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid
https://cvrpapi.azurewebsites.net/Routing?truckTypeID=5&truckWeight=12000&truckHeight=4.6&startLat=49.272055542&startLong=-123.2070587422&endLat=49.009866161&endLong=-123.1248329427&truckWidth=2.6&truckLength=12.5&truckAxels=2&restrictionMode=avoid

**Comment by mraross** [comment]
truckWeight,truckHeight,startLat,startLong,endLat,endLong,truckWidth,truckLength,truckAxels,restrictionMode
18200,4.15,49.3546814899,-122.7758149484,49.2259251979,-122.9642991403,2.6,12.5,2,avoid
18200,4.15,49.2463174483,-123.193896232,49.2462053862,-123.1733826974,2.6,12.5,2,avoid
18200,4.15,49.3799145203,-123.3394650796,49.0951154457,-122.4770383218,2.6,12.5,2,avoid
18200,4.15,49.2864312418,-123.1344584802,49.1509407067,-122.8236226419,2.6,12.5,2,avoid
18200,4.15,49.1931701306,-122.7068929055,49.0876069061,-123.0124501565,2.6,12.5,2,avoid
18200,4.15,49.2467897032,-122.7268056253,49.1731901597,-122.4262265542,2.6,12.5,2,avoid
18200,4.15,49.158822935,-123.190291343,49.0126695795,-123.0811147073,2.6,12.5,2,avoid
18200,4.15,49.158822935,-123.190291343,49.0241275506,-123.1566457131,2.6,12.5,2,avoid
18200,4.15,49.2489014571,-123.0176429131,49.224468966,-123.030410228,2.6,12.5,2,avoid
18200,4.15,49.3417985382,-123.077531276,49.15309085,-122.822957454,2.6,12.5,2,avoid
9000,4.15,49.2241932865,-122.9177493212,49.179533492,-122.8568309901,2.6,12.5,2,avoid
18200,4.15,49.3954699639,-123.2513732074,49.0910025574,-122.4664515612,2.6,12.5,2,avoid
18200,4.15,49.3954699639,-123.2513732074,49.0649350225,-122.5180787204,2.6,12.5,2,avoid
18200,4.15,49.2540144978,-123.1272857674,49.0334687845,-123.0696075448,2.6,12.5,2,avoid
18200,4.15,49.3441826766,-123.1782101367,49.3287023459,-123.1623494608,2.6,12.5,2,avoid
9000,4.15,49.3441826766,-123.1782101367,49.3287023459,-123.1623494608,2.6,12.5,2,avoid
8000,4.15,49.3441826766,-123.1782101367,49.3403321869,-123.1707428668,2.6,12.5,2,avoid
12000,4.15,49.3441826766,-123.1782101367,49.3403321869,-123.1707428668,2.6,12.5,2,avoid
18200,4.5,49.3417985382,-123.077531276,49.15309085,-122.822957454,2.6,12.5,2,avoid
18200,5.25,49.3095108803,-123.0761365273,49.15309085,-122.822957454,2.6,12.5,2,avoid
64000,4.15,49.2241932865,-122.9177493212,49.179533492,-122.8568309901,2.6,12.5,2,avoid
18200,4.5,49.3954699639,-123.2513732074,49.0649350225,-122.5180787204,2.6,12.5,2,avoid
18200,4.5,49.3954699639,-123.2513732074,49.0649350225,-122.5180787204,2.6,12.5,2,avoid
18200,5.15,49.2540144978,-123.1272857674,49.0334687845,-123.0696075448,2.6,12.5,2,avoid
12000,4.5,49.3761578346,-123.2666372035,49.1452219052,-122.7851270411,2.6,12.5,2,avoid
12000,4.5,49.214450836,-122.6681398127,49.1774326821,-122.750708935,2.6,12.5,2,avoid
12000,4.9,49.2355420143,-122.6344178464,49.1774326821,-122.750708935,2.6,12.5,2,avoid
12000,4.3,49.2355420143,-122.6344178464,49.1774326821,-122.750708935,2.6,12.5,2,avoid
12000,5.7,49.272055542,-123.2070587422,49.0781339491,-122.6937912251,2.6,12.5,2,avoid
12000,4.6,49.272055542,-123.2070587422,49.009866161,-123.1248329427,2.6,12.5,2,avoid

**Comment by mraross** [comment]
Provided by Al on 2020/2/20

Hi Graeme and Michael,

I’ve compiled a list of ‘local distortion’ benchmark routes which represent all of the exceptions in the TL BETA below.  Using the refractions router the following waypoints currently produce a correct route.  The list ‘Changes Likely Needed’ show cases where the current router will not produce the correct route without entering intermediate waypoints.  The list ‘No Changes Needed’ are already producing a correct route and I included them just to ensure they continue to work in the future as tweaks are made.

-Alan

Changes Likely Needed
Prefer Front St over Royal Ave
49.20054,-122.92152
49.20313,-122.90645
49.21915,-122.89310
Prefer Haney Bypass over Lougheed Hwy
Not possible with current app
Prefer No 3 Rd and Sea Island Connector over Russ Baker Way
49.16740,-123.15866
49.17017,-123.13721
49.18527,-123.13569
49.19353,-123.14429
49.19219,-123.16072
Discourage Travel on Gatensbury Rd
49.27457,-122.85033
49.26957,-122.87985
49.26345,-122.84722
Discourage Travel on Thermal Drive
49.27654,-122.85161
49.27003,-122.81433
49.26345,-122.84722

No Changes Needed
Allow travel to Coquitlam Lake
49.29557,-122.80107
49.35408,-122.77468
Allow travel to Ocean Point Dr (NB)
49.42935,-123.23326
49.43042,-123.23545
Allow travel to Ocean Point Dr (SB)
49.43223,-123.23391
49.43042,-123.23545
Allow travel out of Ocean Point Drive (NB)
49.43042,-123.23545
49.43279,-123.23375
Allow travel to Horseshoe Bay Ferry
49.36750,-123.27626
49.37568,-123.27214
Allow travel to Tsawwassen Ferry
49.03647,-123.08217
49.00579,-123.13322
Port Access
-seems to comply well with Clark Rd and McGill/Commissioner St access points


ALAN TABBERNOR
Senior GIS Specialist
Infrastructure Program Management
T: 778.375.6432  |  translink.ca

TransLink 
400-287 Nelson’s Court, New Westminster, BC, V3L 0E7, Canada

**Comment by mraross** [comment]
email from Graeme on 2020/02/21:

Hi Alan,

For your Prefer No 3 Rd and Sea Island Connector over Russ Baker Way case, Miller Rd between Russ Baker Way and Templeton St is not a designated truck route.  Shouldn't the preferred route loop up to Grant McConachie Way to avoid an unwanted truck partition signature?  If you remove your fourth coordinate (49.19353,-123.14429) then it will naturally stay on an "all blue" path with a truck multiplier of at least 2.

-Graeme

**Comment by mraross** [comment]
Prefer Front St over Royal:

![image](https://user-images.githubusercontent.com/11318574/76825085-2767d580-67d6-11ea-8211-1f58eab9170b.png)

**Comment by mraross** [comment]
Prefer Haney Bypass over Lougheed Hwy

![image](https://user-images.githubusercontent.com/11318574/76825356-f5a33e80-67d6-11ea-953c-8f3440f53073.png)

**Comment by mraross** [comment]
Discourage travel on Gatensbury Rd

![image](https://user-images.githubusercontent.com/11318574/76825707-de188580-67d7-11ea-9c9a-58366439351d.png)

**Comment by mraross** [comment]
Discourage travel on Thermal Dr

![image](https://user-images.githubusercontent.com/11318574/76826195-0eacef00-67d9-11ea-92e1-99744896fe64.png)

**Comment by mraross** [comment]
Allow travel to Coquitlam Lake

![image](https://user-images.githubusercontent.com/11318574/76826371-909d1800-67d9-11ea-9c7d-4c28583b0a36.png)

**Comment by mraross** [comment]
Allow travel to Ocean Point Dr (NB)
49.42935,-123.23326
49.43042,-123.23545

Data error in ITN:

![image](https://user-images.githubusercontent.com/11318574/76826826-a3fcb300-67da-11ea-963c-2b3425b46210.png)

**Comment by mraross** [comment]
Allow travel to Ocean Point Dr (SB)
49.43223,-123.23391
49.43042,-123.23545

Incorrect left-turn restriction from hwy 99 SB to Ocean Point Dr:

![image](https://user-images.githubusercontent.com/11318574/76827075-33a26180-67db-11ea-8840-f7a6b67af10e.png)

**Comment by mraross** [comment]
Allow travel to Horseshoe Bay Ferry
49.36750,-123.27626
49.37568,-123.27214

![image](https://user-images.githubusercontent.com/11318574/76827176-7f550b00-67db-11ea-9cff-5d9e509728de.png)

**Comment by mraross** [comment]
Allow travel to Tsawwassen Ferry
49.03647,-123.08217
49.00579,-123.1332

![image](https://user-images.githubusercontent.com/11318574/76827343-d35fef80-67db-11ea-9d4d-3e54254ae1c5.png)

**Comment by mraross** [comment]
@al-tabb These two don't work but Graeme said Ocean Point Dr is steep and you provided turn-restrictions to prevent trucks going down it. Please confirm.

Allow travel to Ocean Point Dr (NB)
49.42935,-123.23326
49.43042,-123.23545
Allow travel to Ocean Point Dr (SB)
49.43223,-123.23391
49.43042,-123.23545

**Comment by mraross** [comment]
@al-tabb Awaiting final review by TransLink

**Comment by al-tabb** [comment]
I think that the 'repulsion factor' of Lougheed may be too high:
![image](https://user-images.githubusercontent.com/59742145/76985805-06020900-68fe-11ea-827a-609ffd771838.png)
In this case the route should use Lougheed Hwy as it is still a truck route.  I think the general rule is that for through travel Haney Bypass should be preferred over Lougheed Hwy.  When Lougheed Hwy is the logical access point to the destination it should be used. @gk-tl Please weigh in on this if needed

**Comment by gleeming** [comment]
There is no repulsion factor on Haney Bypass.  I think you forgot to set the follow truck route flag, because when I try your route with that on (and a multiplier over 1.5) it remains on Lougheed Hwy.

**Comment by al-tabb** [comment]
Please ignore previous comment about Lougheed Hwy vs. Haney Bypass - everything looks good, I did not have ldfs and gdfs checked on

**Comment by al-tabb** [comment]
I can confirm that all of these cases work as expected except 'Allow travel to Ocean Point Drive'.  I'd have to take a look at the turn restrictions but I don't see why we would prevent trucks from going to Ocean Point Drive.
