### ISSUE TITLE
Router api on test doesn't work when called from demo app at refractions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#231]
Router api  on test doesn't work when called from demo app at refractions as follows:

https://office.refractions.net/~chodgson/gc/ols-demo/?rt=tst&gc=tst

The router api on delivery does work when called from demo app:

https://office.refractions.net/~chodgson/gc/ols-demo/?rt=dlv&gc=dlv

**Comment by BK01** [comment]
Confirmed: The correct code and data was found in DLV and TEST for the Router & Geocoder

Remaining issue: Intermittent pass/failure during UAT with noted remote address rotation.

**Comment by mraross** [comment]
Just got first failure of router on 142,34,140,33:443
No idea what's going on.

**Comment by mraross** [comment]
Possible Kong bug. Deployed a test router on OpenShift without Kong in the path. See:

https://routertst.pathfinder.gov.bc.ca/

**Comment by mraross** [comment]
Tested and accepted using location services in action at:

https://office.refractions.net/~chodgson/gc/ols-demo/?rt=tst&gc=tst
