### ISSUE TITLE
Non-compliant Route Produced

### ISSUE THREAD

**Issue by al-tabb** [bcgov/ols-router#233]
Found this non-compliant route.  

![image](https://user-images.githubusercontent.com/59742145/76648696-65d26b80-651c-11ea-830b-65aa4c9a2950.png)

**Comment by cmhodgson** [comment]
TruckRouteMultiplier of 4+ solves this. Not sure we've settled on what the multiplier should be but I think we might be generally thinking around 5-10?

**Comment by gk-tl** [comment]
Additional non-compliant route found - should route via Sperling Avenue to minimize distance traveled off the designated truck route network. Also, routing on local access portion of the route (dotted red) exhibits stair-casing through residential area..  

![image](https://user-images.githubusercontent.com/59627982/76665164-05efbb00-6544-11ea-92de-e8d285ba78d1.png)

**Comment by mraross** [comment]
Looking better:

![image](https://user-images.githubusercontent.com/11318574/76824227-bf17f480-67d3-11ea-8a6d-855fb4756057.png)

**Comment by gk-tl** [comment]
Spot on. Thank you.

**Comment by mraross** [comment]
Verified in delivery
