### ISSUE TITLE
HWY 1 EB Bridle Falls offramp not classified as truck route. 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#235]
Bridle Falls offramp not classified as truck route. MOTI to confirm.

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/710eafce-7ef8-400f-a4a6-9a511820673d)

**Comment by gleeming** [comment]
Last month I reviewed all named off and onramps in SLRD, MVRD and FVRD that were not designated truck routes.  If they were used to connect a highway to a truck route (as in this Bridal Falls case) then they were associated with truck routes.  Additionally if the configuration were such that a truck could exit the highway using an offramp, skirt an overpass, and return to the highway via the onramp then those extension segments were also associated with truck routes (e.g. Taylor Way).

The May router data has the truck route correctly set for Bridal Falls offramp.

**Comment by mraross** [comment]
Verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82836565-910dfb00-9e7b-11ea-9da5-f07972abbf9e.png)
