### ISSUE TITLE
QA of Global Distortion field

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#236]
Review previously identified and fixed odd cases and make sure they stay fixed in the presence of global distortion field. 

Used location services in action app at Refractions:
https://office.refractions.net/~chodgson/gc/ols-demo/?rt=rri

Here is the tuning string used in testing:

globalDistortionField=alleyway:1.2,alleyway.truck:1.1,arterial_major:1.01,arterial_major.truck:1.01,arterial_minor:1.01,arterial_minor.truck:1.01,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:1.2,driveway.truck:1.1,ferry:1,ferry.truck:1,freeway:1,freeway.truck:1,highway_major:1,highway_major.truck:1,highway_minor:1,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.1,local.truck:1.05,ramp:1,ramp.truck:1,recreation:1.2,recreation.truck:1.1,resource:1.2,resource.truck:1.1,restricted:1.2,restricted.truck:1.1,service:1.2,service.truck:1.1,strata:1.2,strata.truck:1.1,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3.0,10.0,7.0,1.1&turnCost=3.0,1.0,10.0,5.0

To perform testing:

1. Start up Location Services in Action at:

    https://office.refractions.net/~chodgson/gc/ols-demo/?rt=rri

2 Open the Route tab and you will see this:

![image](https://user-images.githubusercontent.com/11318574/77200065-1b666700-6aa7-11ea-9b6f-db3f1ee6b772.png)

3. Turn on Global and Local Distortion Fields, crossing cost, turn cost, Truck Mode, Follow Truck Route, and enter a route multiplier of 9. The Route tab should now look like this:

![image](https://user-images.githubusercontent.com/11318574/77200419-b7906e00-6aa7-11ea-8d0f-44df142fe02e.png)

4. Click on the hyperlinked text Global Distortion Field to pop up the Configuration Panel.

5.  Copy the tuning string above into the clipboard.

6. Paste the clipboard contents into the Tuning String field of the Configuration Panel and press Enter. The configuration panel should now look like this:

![image](https://user-images.githubusercontent.com/11318574/77258502-42a06e00-6c38-11ea-8fbe-724d2b46afba.png)

You are now ready to test.

**Comment by mraross** [comment]
5411 Kingsway, Burnaby, BC
649 Columbia St, New Westminster, BC

![image](https://user-images.githubusercontent.com/11318574/77006222-4faf1b80-691f-11ea-80ed-a42410a633ef.png)

**Comment by mraross** [comment]
770 Rosser Ave, Burnaby
6319 Lochdale St, Burnaby
from https://github.com/bcgov/ols-router/issues/233

![image](https://user-images.githubusercontent.com/11318574/77007967-76bb1c80-6922-11ea-9aed-692b395d9f44.png)

**Comment by mraross** [comment]
49.20054,-122.92152
49.21915,-122.89310

from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77008387-4d4ec080-6923-11ea-9146-6104221b6784.png)

**Comment by mraross** [comment]
Prefer No 3 Rd and Sea Island Connector over Russ Baker Way
49.16740,-123.15866
49.19219,-123.16072
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77008779-0ad9b380-6924-11ea-9f2b-e12d05c000c5.png)

**Comment by mraross** [comment]
Discourage Travel on Gatensbury Rd
49.27457,-122.85033
49.26345,-122.84722
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77009095-8dfb0980-6924-11ea-9a05-ae3b457a038f.png)

**Comment by mraross** [comment]
Discourage Travel on Thermal Drive
49.27654,-122.85161
49.26345,-122.84722
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77009257-d5819580-6924-11ea-97d2-0999681cd583.png)

**Comment by mraross** [comment]
Allow travel to Coquitlam Lake
49.29557,-122.80107
49.35408,-122.77468
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77009468-36a96900-6925-11ea-8edf-34883650e24e.png)

**Comment by mraross** [comment]
Allow travel to Horseshoe Bay Ferry
49.36750,-123.27626
49.37568,-123.27214
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77009722-a4ee2b80-6925-11ea-82a2-b6cda1c3975e.png)

**Comment by mraross** [comment]
Allow travel to Tsawwassen Ferry
49.03647,-123.08217
49.00579,-123.13322
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77010003-2e9df900-6926-11ea-95ee-a3b15b586ee5.png)

**Comment by mraross** [comment]
Prefer Haney Bypass over Lougheed Highway
from issue https://github.com/bcgov/ols-router/issues/229

![image](https://user-images.githubusercontent.com/11318574/77010447-02cf4300-6927-11ea-97c4-6949beaf89d1.png)

**Comment by mraross** [comment]
New test case showing effect of global distortion field

w/o global distortion field
![image](https://user-images.githubusercontent.com/11318574/77010775-b5070a80-6927-11ea-9584-677d22f73d5d.png)

with global distortion field
![image](https://user-images.githubusercontent.com/11318574/77010836-d23bd900-6927-11ea-8b87-77c6134f7a48.png)

**Comment by mraross** [comment]
East to west through New Westminster taking Front St instead of Royal Ave
49.23766,-122.70301
49.15640,-123.03366

from issue https://github.com/bcgov/ols-router/issues/210

![image](https://user-images.githubusercontent.com/11318574/77011730-c05b3580-6929-11ea-8829-3feecf2f4b2c.png)

**Comment by gleeming** [comment]
At the Tsawwassen ferry terminal, the truck routes in ITN match exactly with what is in Translink's Feb 2018 data (and CVRP app).  It is odd that there isn't a southbound lane designated as a truck route for whichever section trucks get directed to wait in line at the terminal.  It's yet another data anomaly that someone could look into and report to GeoBC if changes are required.

**Comment by mraross** [comment]
@al-tabb Given Graeme's analysis, do you want to designate a southbound lane in the ferry terminal as a truck route?

**Comment by mraross** [comment]
Latest tune string:

globalDistortionField=alleyway:2,alleyway.truck:2,arterial_major:1.1,arterial_major.truck:1.1,arterial_minor:1.1,arterial_minor.truck:1.1,collector_major:1.1,collector_major.truck:1.1,collector_minor:1.1,collector_minor.truck:1.1,driveway:2,driveway.truck:2,ferry:1,ferry.truck:1,freeway:1.0,freeway.truck:1.0,highway_major:1.0,highway_major.truck:1.0,highway_minor:1.0,highway_minor.truck:1.0,lane:1.05,lane.truck:1.05,local:1.2,local.truck:1.2,ramp:1,ramp.truck:1,recreation:2,recreation.truck:1.2,resource:2,resource.truck:1.2,restricted:2,restricted.truck:1.2,service:2,service.truck:1.2,strata:2,strata.truck:1.2,yield_lane:1.1,yield_lane.truck:1.1,&xingCost=3,10,7,1.5&turnCost=3.0,1.0,10,5

**Comment by mraross** [comment]
Latest tune string:

globalDistortionField=alleyway:2,alleyway.truck:1.2,arterial_major:1.1,arterial_major.truck:1.1,arterial_minor:1.1,arterial_minor.truck:1.1,collector_major:1.1,collector_major.truck:1.1,collector_minor:1.1,collector_minor.truck:1.1,driveway:2,driveway.truck:1.2,ferry:1,ferry.truck:1,freeway:1.0,freeway.truck:1.0,highway_major:1.0,highway_major.truck:1.0,highway_minor:1.0,highway_minor.truck:1.0,lane:1.05,lane.truck:1.05,local:1.2,local.truck:1.2,ramp:1,ramp.truck:1,recreation:2,recreation.truck:1.2,resource:2,resource.truck:1.2,restricted:2,restricted.truck:1.2,service:2,service.truck:1.2,strata:2,strata.truck:1.2,yield_lane:1.1,yield_lane.truck:1.1,&xingCost=3,10,7,1.5&turnCost=3.0,1.0,10,5

**Comment by gleeming** [comment]
The GDF tuning on major corridors such as arterial and collector has a very substantial and sometimes unwanted effect.  Factors of 1.1 for trucks on these road classes (10% impact) are just too high.  Perhaps 1.01 would be more suitable for initial testing.  Here's one of the most extreme examples with the latest tune string.
![friction_factor](https://user-images.githubusercontent.com/21045965/77034181-8bb99f00-6966-11ea-8fbe-e7f8f165b73f.jpg)

**Comment by mraross** [comment]
I have reduced all 1.1 factors to 1.01. 1.2 and 2.0 factors unchanged.

globalDistortionField=alleyway:2,alleyway.truck:1.2,arterial_major:1.01,arterial_major.truck:1.01,arterial_minor:1.01,arterial_minor.truck:1.01,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:2,driveway.truck:1.2,ferry:1,ferry.truck:1,freeway:1.0,freeway.truck:1.0,highway_major:1.0,highway_major.truck:1.0,highway_minor:1.0,highway_minor.truck:1.0,lane:1.01,lane.truck:1.01,local:1.2,local.truck:1.2,ramp:1,ramp.truck:1,recreation:2,recreation.truck:1.2,resource:2,resource.truck:1.2,restricted:2,restricted.truck:1.2,service:2,service.truck:1.2,strata:2,strata.truck:1.2,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3,10,7,1.5&turnCost=3.0,1.0,10,5

**Comment by mraross** [comment]
Set GDF so that trucks on designated routes avoid highways

![image](https://user-images.githubusercontent.com/11318574/77099924-f9e77b80-69d1-11ea-9891-a006893c3db8.png)

**Comment by mraross** [comment]
Set GDF so that truck on designated routes prefer highways

![image](https://user-images.githubusercontent.com/11318574/77100083-43d06180-69d2-11ea-9f0e-9b357ca183d2.png)

**Comment by mraross** [comment]
Set GDF so that trucks prefer local roads to main roads

![image](https://user-images.githubusercontent.com/11318574/77101036-e2a98d80-69d3-11ea-885f-8eb8b33aa3a2.png)

**Comment by mraross** [comment]
Set GDF so that trucks prefer main roads to local roads

![image](https://user-images.githubusercontent.com/11318574/77101198-2a301980-69d4-11ea-9833-b9097f9143d1.png)

**Comment by mraross** [comment]
defaultGlobalDistortionField:
alleyway:2,alleyway.truck:1.2,arterial_major:1.01,arterial_major.truck:1,arterial_minor:1.01,arterial_minor.truck:1,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:2,driveway.truck:1.2,ferry:1,ferry.truck:1,freeway:1.0,freeway.truck:1,highway_major:1.0,highway_major.truck:1,highway_minor:1.0,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.2,local.truck:1.2,ramp:1,ramp.truck:1,recreation:2,recreation.truck:1.2,resource:2,resource.truck:1.2,restricted:2,restricted.truck:1.2,service:2,service.truck:1.2,strata:2,strata.truck:1.2,yield_lane:1.01,yield_lane.truck:1.01

defaultXingCost:
3,10,7,1.5

defaultTurnCost:
3.0,1.0,10,5

**Comment by mraross** [comment]
GDF Test 12
Surrey, BC
6348 264 St, Township of Langley, BC

![image](https://user-images.githubusercontent.com/11318574/77221712-72048d00-6b09-11ea-9b1e-5c5a1a5657c9.png)


![image](https://user-images.githubusercontent.com/11318574/77221697-4a152980-6b09-11ea-851b-bb278543f4f7.png)

**Comment by mraross** [comment]
GDF Test 13

**Comment by mraross** [comment]
Reran all GDF tests successfully with the following tuning string:

globalDistortionField=alleyway:1.2,alleyway.truck:1.1,arterial_major:1.01,arterial_major.truck:1,arterial_minor:1.01,arterial_minor.truck:1,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:1.2,driveway.truck:1.1,ferry:1,ferry.truck:1,freeway:1,freeway.truck:1,highway_major:1,highway_major.truck:1,highway_minor:1,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.1,local.truck:1.05,ramp:1,ramp.truck:1,recreation:1.2,recreation.truck:1.1,resource:1.2,resource.truck:1.1,restricted:1.2,restricted.truck:1.1,service:1.2,service.truck:1.1,strata:1.2,strata.truck:1.1,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3.0,10.0,7.0,1.5&turnCost=3.0,1.0,10.0,5.0

**Comment by mraross** [comment]
GDF Test 14
814 Nicola St, Vancouver, BC
132 W Georgia St, Vancouver, BC
![image](https://user-images.githubusercontent.com/11318574/77221925-9f523a80-6b0b-11ea-8695-8069873b51d9.png)

**Comment by mraross** [comment]
GDF Test Case 15 (Benchmark 7)

**Comment by mraross** [comment]
Reran all GDF tests successfully with the following tuning string:

globalDistortionField=alleyway:1.2,alleyway.truck:1.1,arterial_major:1.01,arterial_major.truck:1,arterial_minor:1.01,arterial_minor.truck:1,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:1.2,driveway.truck:1.1,ferry:1,ferry.truck:1,freeway:1,freeway.truck:1,highway_major:1,highway_major.truck:1,highway_minor:1,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.1,local.truck:1.05,ramp:1,ramp.truck:1,recreation:1.2,recreation.truck:1.1,resource:1.2,resource.truck:1.1,restricted:1.2,restricted.truck:1.1,service:1.2,service.truck:1.1,strata:1.2,strata.truck:1.1,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3.0,10.0,7.0,1.5&turnCost=3.0,1.0,10.0,5.0

**Comment by mraross** [comment]
Reran all GDF tests successfully with the following tuning string:

globalDistortionField=alleyway:1.2,alleyway.truck:1.1,arterial_major:1.01,arterial_major.truck:1.01,arterial_minor:1.01,arterial_minor.truck:1.01,collector_major:1.01,collector_major.truck:1.01,collector_minor:1.01,collector_minor.truck:1.01,driveway:1.2,driveway.truck:1.1,ferry:1,ferry.truck:1,freeway:1,freeway.truck:1,highway_major:1,highway_major.truck:1,highway_minor:1,highway_minor.truck:1,lane:1.01,lane.truck:1.01,local:1.1,local.truck:1.05,ramp:1,ramp.truck:1,recreation:1.2,recreation.truck:1.1,resource:1.2,resource.truck:1.1,restricted:1.2,restricted.truck:1.1,service:1.2,service.truck:1.1,strata:1.2,strata.truck:1.1,yield_lane:1.01,yield_lane.truck:1.01,&xingCost=3.0,10.0,7.0,1.5&turnCost=3.0,1.0,10.0,5.0

**Comment by mraross** [comment]
@gk-tl Reran gdf test cases 4-6 above after Graeme updated local distortion fields as per your previous review. Please review.

**Comment by gk-tl** [comment]
Looks good. Thank you.

**Comment by mraross** [comment]
Be sure to watch the delightful distortion field demo at:

https://github.com/bcgov/ols-router/issues/249

**Comment by mraross** [comment]
Repeated all test cases successfully for v2.1.2

**Comment by BK01** [comment]
All GDF tests listed above are being integrated into the DataBC router test list.

**Comment by mraross** [comment]
Verified in production

**Comment by mraross** [comment]
Verified in delivery with May 2020 data.

**Comment by alixcote** [comment]
Re-closing.
