### ISSUE TITLE
Incorrect No Straight Through turn-restriction

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#238]
Is this the best truck route between 15040 Williams Rd, Richmond, BC and 18033 29A Ave, Surrey, BC?

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/3b8c4622-e18e-492e-b67f-ba51e65fed4c)

**Comment by cmhodgson** [comment]
There is an incorrect no straight through identified as buses-only on the internal segment of the ramp intersection where the turn should be made. The segments there are already identified as truck routes.

**Comment by gleeming** [comment]
I have removed the straight turn restriction, which should take effect when we build the April data package

**Comment by mraross** [comment]
Super, thanks

**Comment by gleeming** [comment]
Confirmed this is fixed in the April build
