### ISSUE TITLE
Select and implement most promising advanced routing algorithms

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#24]
@mraross commented on [Mon Mar 26 2018](https://github.com/bcgov/api-specs/issues/321)

1. Evaluate existing algorithms that support dynamic and time-dependent route planning with user preferences and make a recommendation. 

2. Evaluate existing timetable-based routing algorithms to support ferry routing and make a recommendation. 

3. Determine how to best integrate recommended algorithms.

4. Write up findings and recommendations in an Advanced Routing Algorithm Evaluation document
5. Implement recommended algorithms

---

@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/321#issuecomment-394030094)

Issue moved to [bcgov/ols-router #2](https://github.com/bcgov/ols-router/issues/2) via [**ZenHub**](https://www.zenhub.com/)

---

@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/321#issuecomment-394031411)

Issue moved to [bcgov/ols-router #4](https://github.com/bcgov/ols-router/issues/4) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cmhodgson** [comment]
Promising implementation approaches include:

Dynamic Time-Dependent Routing in Road Networks Through Sampling (TD-S+P)
http://drops.dagstuhl.de/opus/volltexte/2017/7897/pdf/OASIcs-ATMOS-2017-3.pdf

Dynamic, time-dependent route planning in road networks with user preferences (TDCRP)
https://arxiv.org/pdf/1512.09132 

Fast Exact Shortest Path and Distance Queries on Road Networks with Parameterized Costs
(Generalized PRP)
https://arxiv.org/pdf/1509.03165.pdf

Each of these approaches has a deep set of cited references which cover the other algorithms at the root  of the complete approaches, many of which are linked to from #25 .

**Comment by mraross** [comment]
Original paper on Ruin and recreate algorithm (2000). This algorithm is used in jSprit, the open source route optimization library used by the current route planner.
http://polymorphe.free.fr/cours/ia/tsp/schrimpf-record_breaking_opt_ruin_recreate.pdf

Slack induction by string removal for VRP (2018)
https://lirias.kuleuven.be/retrieve/545845
