### ISSUE TITLE
Gap in truck route at River Rd and No. 2 Rd, Richmond

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#243]
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/d1c32497-cee9-4c0a-8b3b-4cd8bf9f582d)

**Comment by mraross** [comment]
@gk-tl Please review

**Comment by gk-tl** [comment]
Confirming that River Rd should be considered part of the TRN.

![image](https://user-images.githubusercontent.com/59627982/77282940-730ff880-6c88-11ea-9bcd-ed5e97e28d9f.png)

**Comment by gk-tl** [comment]
@al-tabb please update the height clearance data - both cartographic and for the ITN. Height clearance 4 m in both travel directions 

![image](https://user-images.githubusercontent.com/59627982/77283454-9d15ea80-6c89-11ea-866b-c6143171ba49.png)

**Comment by gleeming** [comment]
Submitted JIRA ticket GBAITN-19144 last month.  Confirmed truck route is in the April ITN data.

**Comment by gk-tl** [comment]
Thanks Graeme. Much appreciated.
