### ISSUE TITLE
31 St West Vancouver is missing a height restriction

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#246]
31st St, West Vancouver is missing a height restriction

49.33994,-123.20060
49.34134,-123.20686
height=7m

![image](https://user-images.githubusercontent.com/11318574/77367227-eeb88680-6d16-11ea-891a-d03b4f242201.png)

**Comment by alixcote** [comment]
This looks resolved. Closing.
![image](https://user-images.githubusercontent.com/89096395/209998296-2c807f06-b0a6-4163-bd60-463ebe1cdb2b.png)
