### ISSUE TITLE
Performance test on delivery

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#247]
Ran 30 random origin/destination pair route requests in the Metro Van area using location services in action and router and geocoder in delivery as follows:

https://bcgov.github.io/ols-devkit/ols-demo/index.html?rt=dlv&gc=dlv

Raw execution times (in ms): 13,432,292,144,62,97,265,103,261,176,175,306,127,148,199,30,346,448,215,121,149,336,346,422,312,60,251,310,149,458

Used calculator.net to compute stats on raw execution times:
https://www.calculator.net/statistics-calculator.html

and here's the results:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/b1bc0849-f3b2-4e2c-afff-33ab41ed6de2)

**Comment by mraross** [comment]
Ran 30 random origin/destination pair route requests across the province using location services in action and router and geocoder in delivery as follows:

https://bcgov.github.io/ols-devkit/ols-demo/index.html?rt=dlv&gc=dlv

Raw execution times (in ms): 18,908,726,988,964,129,179,823,805,1115,1200,1204,255,1153,944,374,832,1046,1034,1143,1023,256,91,1149,1073,932,928,15,897,943

Used calculator.net to compute stats on raw execution times:
https://www.calculator.net/statistics-calculator.html

and here's the results:

![image](https://user-images.githubusercontent.com/11318574/77378609-ae1b3600-6d33-11ea-8b38-ad954c988733.png)

**Comment by alixcote** [comment]
Re-closing.
