### ISSUE TITLE
Deliver demo of distortion fields at final TransLink Review

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#249]
https://bcgov.github.io/ols-devkit/ols-demo/index.html?rt=tst&gc=tst

Discourage travel on Gatensbury Rd
49.27457,-122.85033
49.26345,-122.84722

Fastest route (No distortion fields, not following truck routes)
- taking Gatensbury Rd instead of truck routes

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/05762b4a-6692-4e18-b68c-7085ccaa7116)

**Comment by mraross** [comment]
Turn on global distortion field. More major route taken.

![image](https://user-images.githubusercontent.com/11318574/77571192-298efb80-6e8a-11ea-9246-c4ec06a55dd6.png)

**Comment by mraross** [comment]
Turn on follow truck route. No effect.

![image](https://user-images.githubusercontent.com/11318574/77571365-7a9eef80-6e8a-11ea-963a-c082ff16dd6b.png)

**Comment by mraross** [comment]
Turn on local distortion field. Voila! A compliant route.

![image](https://user-images.githubusercontent.com/11318574/77571453-a6ba7080-6e8a-11ea-9cba-6b62f174de91.png)

**Comment by al-tabb** [comment]
Awesome, looks good.  This is one of the trickiest areas in the region to produce compliant routes.

**Comment by gk-tl** [comment]
Nicely done. As Alan noted, this is one of the trickiest areas in MV for the router.

**Comment by mraross** [comment]
Demo delivered at final TransLink project review meeting.
