### ISSUE TITLE
Find advanced routing algorithms

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#25]
@mraross commented on [Fri Mar 03 2017](https://github.com/bcgov/api-specs/issues/153)

## Problem statement

When computing best route, the Route Planner needs to take into account the following:
1. Start or end time
1. Multiple stops
1. User preferences
1. Vehicle type, dimensions, and configuration
1. Cargo type
1. Turn costs
1. Turn restrictions
1. Road restrictions
1. Road type and ownership
1. Truck routes and policy corridors
1. Scheduled and real-time road events
1. Ferry schedules
1. Historic traffic congestion

Turn and road restrictions may be dependent on time, vehicle type, vehicle dimensions, vehicle configuration, regional policy, and spatial extent

Taking these factors into account will require:

"... a practical algorithm that, while robust to user preferences, is able to integrate global changes of the time-dependent metric (e. g., due to traffic updates or user restrictions) faster than previous approaches, while allowing subsequent queries that enable interactive applications."
Source: https://arxiv.org/pdf/1512.09132.pdf

---

@mraross commented on [Sun Jun 10 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-322673527)

Recent and promising:

A Fast and Tight Heuristic for A* in Road Networks
https://arxiv.org/pdf/1910.12526.pdf

Space-efficient, fast, and exact routing in time-dependent road networks
https://www.mdpi.com/1999-4893/14/3/90/pdf
https://arxiv.org/pdf/1910.12726.pdf

Towards Alleviating Traffic Congestion: Optimal Route Planning for Massive-Scale Trips
https://www.ijcai.org/proceedings/2020/0470.pdf

Framing algorithms for approximate multicriteria shortest paths
https://drops.dagstuhl.de/opus/volltexte/2020/13147/pdf/OASIcs-ATMOS-2020-11.pdf

Customizable Contraction Hierarchies with Turn Costs
https://drops.dagstuhl.de/opus/volltexte/2020/13145/pdf/OASIcs-ATMOS-2020-9.pdf

Time-Dependent Alternative Route Planning
https://drops.dagstuhl.de/opus/volltexte/2020/13144/pdf/OASIcs-ATMOS-2020-8.pdf

A Strategic Routing Framework and Algorithms for Computing Alternative Paths
https://drops.dagstuhl.de/opus/volltexte/2020/13146/pdf/OASIcs-ATMOS-2020-10.pdf

Space-efficient, fast, and exact routing in time-dependent road networks
https://www.mdpi.com/1999-4893/14/3/90/pdf
https://arxiv.org/pdf/1910.12726.pdf

Faster and Better Nested Dissection Orders for Customizable Contraction Hierarchies
https://arxiv.org/pdf/1906.11811.pdf

Alternative multicriteria routes
https://epubs.siam.org/doi/pdf/10.1137/1.9781611975499.6

Personal Routes with High-Dimensional Costs and Dynamic Approximation Guarantees
http://drops.dagstuhl.de/opus/volltexte/2017/7625/pdf/LIPIcs-SEA-2017-18.pdf

Forward search in contraction hierarchies (2018)
http://harabor.net/data/papers/hs-fsich-18.pdf

Real-Time Traffic Assignment Using Fast Queries in Customizable Contraction Hierarchies
http://drops.dagstuhl.de/opus/volltexte/2018/8962/pdf/LIPIcs-SEA-2018-27.pdf

Traffic aware routing in road networks (on-demand customization)
http://www.sommer.jp/trafficrouting.pdf

Dynamic Time-Dependent Routing in Road Networks Through Sampling
http://drops.dagstuhl.de/opus/volltexte/2017/7897/pdf/OASIcs-ATMOS-2017-3.pdf

Intriguingly Simple and Efficient Time-Dependent Routing in Road Networks
https://arxiv.org/pdf/1606.06636.pdf

Experimental implementation of TD-S (based on RoutingKit)
https://github.com/ben-strasser/td_p

Experimental implementation of FlowCutter (used in TD-S)
https://github.com/ben-strasser/flow-cutter-pace16

Customizable Contraction Hierararchies (CCH)
https://arxiv.org/pdf/1402.0402.pdf

C++ Implementation of CCH
https://github.com/RoutingKit/RoutingKit

Graph cutting with Pareto Optimization (FlowCutter)
https://arxiv.org/pdf/1504.03812.pdf

Computing tree decompositions with FlowCutter
https://arxiv.org/pdf/1709.08949.pdf

Intriguingly simple and Fast Transit Routing
https://pdfs.semanticscholar.org/a892/a54b02ce112e1302931231141a8b676b873b.pdf

Connection Scan Algorithm
https://arxiv.org/pdf/1703.05997.pdf

Fast Exact Shortest Path and Distance Queries on Road Networks with Parameterized Costs
https://arxiv.org/pdf/1509.03165.pdf

---

@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-361354021)

More papers on time-dependent routing
 
Dynamic, time-dependent route planning in road networks with user preferences
https://arxiv.org/abs/1512.09132
 
Customizable Route Planning
http://i11www.iti.kit.edu/extra/publications/dgpw-crp-11.pdf

Computing time dependent travel times in vehicle routing problems
http://essay.utwente.nl/72040/1/20170306%20-%20Publiceren%20thesis%20van%20Mathijs.pdf

How to build a real-time vehicle route optimizer
http://www.opendoorlogistics.com/assets/pdfs/How-to-build-a-real-time-vehicle-route-optimiser.pdf

Engineering Time-Dependent Many-to-Many Shortest Paths Computation
http://drops.dagstuhl.de/opus/volltexte/2010/2751/pdf/7.pdf

Vehicle routing under time-dependent travel times:  the impact of congestion avoidance
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.208.3905&rep=rep1&type=pdf

The Time-Dependent Shortest Path and Vehicle Routing Problem
https://www.cirrelt.ca/DocumentsTravail/CIRRELT-2017-57.pdf

Time-Dependent Route Planning with Generalized Objective Functions
https://algo2.iti.kit.edu/download/gen_obj_func_tch.pdf
http://algo12.fri.uni-lj.si/reg/proc/presentations/MUAQVhDxhsoheZshATmODHmQi.pdf

A Survey of Shortest Path Algorithms
https://arxiv.org/pdf/1705.02044.pdf

Dynamic Vehicular Route Guidance usingTraffic Prediction Information
https://www.hindawi.com/journals/misy/2016/3727865/

Self-aware traffic route planning
http://gamma.cs.unc.edu/TROUTE/AAAI2011-2.pdf

Time dependent route planning
https://pdfs.semanticscholar.org/f21c/47d7fac0a291647cd1211ce79349b5f47a80.pdf

---

@mraross commented on [Tue May 22 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-389704094)

Spatio-temporal traffic flow forecasting on a city-wide sensor network
https://projekt.beuth-hochschule.de/fileadmin/projekt/magda/Presentations/GISOV2017_Kunde_Hartenstein_Sauer.pdf

Nice animation of contraction hierarchies
https://www.mjt.me.uk/posts/contraction-hierarchies/

Nice exposition of CH
http://www.fmi.uni-stuttgart.de/files/alg/teaching/s15/alg/CH.pdf

Using OSRM as a CH testing platform
http://snap.stanford.edu/class/cs224w-2014/projects2014/cs224w-10-final.pdf

---

@mraross commented on [Thu May 24 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-391798756)

Looking ahead to road restrictions, check out:
Fast Exact Shortest Path and Distance Queries on Road Networks with Parameterized Costs
https://arxiv.org/pdf/1509.03165.pdf

---

@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-394029490)

Issue moved to [bcgov/ols-router #1](https://github.com/bcgov/ols-router/issues/1) via [**ZenHub**](https://www.zenhub.com/)

---

@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-394032142)

Issue moved to [bcgov/ols-router #5](https://github.com/bcgov/ols-router/issues/5) via [**ZenHub**](https://www.zenhub.com/)

---

@mraross commented on [Sun Jun 10 2018](https://github.com/bcgov/api-specs/issues/153#issuecomment-395922910)

MOTI Traffic data
http://www.th.gov.bc.ca/trafficData/documents/TrafficReportsUserDocumentation_Apr2014.pdf
http://www.th.gov.bc.ca/trafficData/tradas/tradas.asp?loc=47-002EW

TransLink APIs for 
  - Regional Traffic Data System (RTDS) which provides real-time traffic data in the Greater Vancouver area including speed profiles and travel time by corridor and roadway segment
 - Real Time Transit Info (RTTI)
 - GTFS - Real-time
 - GTFS
https://developer.translink.ca/

Traffic congestion metrics
http://www.tac-atc.ca/sites/default/files/site/doc/Bookstore/defining-measuring-congestion.pdf

Cool traffic simulator that runs in browser
http://www.traffic-simulation.de/
http://traffic-flow-dynamics.org/

Simulation of Urban Mobility (SUMO)
 - supports OSM format
http://www.dlr.de/ts/en/desktopdefault.aspx/tabid-9883/16931_read-41000/

Toward realistic urban traffic congestion experiments using DFRouter
 - a component of SUMO
http://www.mdpi.com/1424-8220/17/12/2921/pdf

Flow architecture and benchmarking for reinforcement learning in traffic control
 - uses SUMO
https://arxiv.org/pdf/1710.05465.pdf

IEEE ITSC 2018 SUMO workshop
https://www.ieee-itsc2018.org/uploads/5/0/3/9/50391481/tutorial_on_simulation_of_urban_mobility__sumo__v2.pdf

TraffSim: A traffic simulator for investigations of congestion minimization through dynamic vehicle rerouting
http://ijssst.info/Vol-15/No-4/paper5.pdf
 - supports OSM format

Proactive vehicle rerouting strategies for congestion avoidance 
https://web.njit.edu/~borcea/papers/dcoss12.pdf

Traffic recovery time estimation under different flow regimes
-  predicts post-incident traffic recovery time based on traffic intensity, incident duration, and incident severity (ratio of lanes closure).
https://ac.els-cdn.com/S2095756415000653/1-s2.0-S2095756415000653-main.pdf?_tid=8a3b4824-0fed-4d44-91d4-3ad3d192ccb8&acdnat=1528518266_beb44b5515ab38020a97d061f4dddd31

Multi agent, transport simulation
https://matsim.org/

Integration of information patterns in the modelling and design of mobility management systems
https://arxiv.org/pdf/1707.07371.pdf

Towards a socially optimal multi-modal routing platform
https://arxiv.org/pdf/1802.10140.pdf

Comparison of traffic simulators
https://www.matec-conferences.org/articles/matecconf/pdf/2016/44/matecconf_ictte2016_05002.pdf

Trends in real-time traffic simulation
http://research.fh-ooe.at/files/publications/5760_journal_article.pdf

**Comment by mraross** [comment]
Dynamic costing in valhalla
https://github.com/valhalla/valhalla/blob/master/docs/sif/dynamic-costing.md

Vehicle routing under time-dependent travel times: the impact of congestion avoidance; details of the computational tests
https://www.utwente.nl/en/bms/iebis/staff/schutten/ICA/tests.pdf

**Comment by mraross** [comment]
Accurate and fast path computation on large urban road networks: A general approach
http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0192274&type=printable

**Comment by mraross** [comment]
Provable Efficiency of Contraction Hierarchies with Randomized Preprocessing
http://ad-publications.informatik.uni-freiburg.de/ISAAC_randCH_FS_2015.pdf

Polynomial-time Construction of Contraction Hierarchies for Multi-criteria Objectives
http://ad-publications.informatik.uni-freiburg.de/ALENEX_multiCH_FS_2013.pdf

Modeling and Engineering Constrained Shortest Path Algorithms for Battery Electric Vehicles
http://drops.dagstuhl.de/opus/volltexte/2017/7867/pdf/LIPIcs-ESA-2017-11.pdf

Understanding Subgoal Graphs by Augmenting Contraction Hierarchies
http://idm-lab.org/bib/abstracts/papers/ijcai18a.pdf

A Randomized Path Routing Algorithm for Decentralized Route Allocation in Transportation Networks
https://people.eng.unimelb.edu.au/etanin/iwcts15.pdf

**Comment by mraross** [comment]
Transit Node Routing Reconsidered
https://arxiv.org/pdf/1302.5611.pdf

**Comment by mraross** [comment]
Here's another promising approach that using community detection to form hierarchical clusters of subgraphs. It has minimal preprocessing time, good performance, and a very small memory footprint.

Hierarchical Time-Dependent Shortest Path Algorithms for Vehicle Routing under ITS
https://www.eecis.udel.edu/lena/files/iie16_lena.pdf

Fast unfolding of communities in large networks
https://arxiv.org/pdf/0803.0476.pdf

**Comment by mraross** [comment]
A Comparative Study of Vehicles’ Routing Algorithms for Route Planning in Smart Cities
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.700.6873&rep=rep1&type=pdf

Balanced Traffic Routing: Design, Implementation, and Evaluation
https://web.njit.edu/~borcea/papers/elsevier-adhoc15.pdf

**Comment by mraross** [comment]
Selfish routing and the price of anarchy
https://theory.stanford.edu/~tim/papers/optima.pdf

**Comment by mraross** [comment]
Traffic engineering links

Traffic state estimation on highway: A comprehensive survey
https://bayen.eecs.berkeley.edu/sites/default/files/journals/TSE_review.pdf

Framework for Control and Deep Reinforcement Learning in Traffic
http://nkheterpal.me/itsc_cistar_paper.pdf

Understanding Road Usage Patterns in Urban Areas
https://www.nature.com/articles/srep01001.pdf

**Comment by mraross** [comment]
Improved Oracles for time-dependent road networks
 - outperforms Time-Dependent Sampling but with longer preprocessing time
https://arxiv.org/pdf/1704.08445.pdf

**Comment by mraross** [comment]
Forward search in contraction hierarchies (2018)
- 10 times faster than bidirectional-Dijkstra contraction hierarchies
http://harabor.net/data/papers/hs-fsich-18.pdf

Compressing optimal paths with run length encoding (2015)
https://jair.org/index.php/jair/article/view/10971/26118


Introduction to Contraction Hierarchies
https://movingai.com/IJCAI18-HS/ijcai-hs-harabor.pdf
- good tutorial that covers latest developments
- big (178 pages)

Daniel Harabor publications
http://www.harabor.net/daniel/index.php/publications/
 - pathfinder researcher associated with Karlsruhe group
 - author of forward search in contraction hierarchies

**Comment by mraross** [comment]
Accurate and fast path computation on large urban road networks: A general approach
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5812589/pdf/pone.0192274.pdf

**Comment by mraross** [comment]
Customizable Route Planning

Many-to-many Customizable Route Planning with Time-dependent Driving Restrictions
https://dspace.library.uu.nl/bitstream/handle/1874/359586/Thesis.pdf?sequence=2&isAllowed=y

**Comment by mraross** [comment]
Mining driving preferences and efficient personalized routing
https://www.ppsa.dk/download/uni/p9.pdf

Alternative multi-criteria routes
https://epubs.siam.org/doi/pdf/10.1137/1.9781611975499.6

**Comment by mraross** [comment]
Personal Routes with High-Dimensional Costs and Dynamic Approximation Guarantees
http://drops.dagstuhl.de/opus/volltexte/2017/7625/pdf/LIPIcs-SEA-2017-18.pdf

**Comment by PayasR** [comment]
Shortest Path Queries in static networks:
www.sommer.jp/spq-survey.pdf

Traffic Aware Routing in Road Networks:
www.sommer.jp/trafficrouting.pdf

Practical Route Planning Under Delay Uncertainty: Stochastic Shortest Path Queries
https://www.roboticsproceedings.org/rss08/p32.html

Polynomial Time Construction of CH for Multicriteria Objectives:
http://ad-publications.informatik.uni-freiburg.de/ALENEX_multiCH_FS_2013.pdf

Personalized Route Planning in Road Networks:
http://ad-publications.informatik.uni-freiburg.de/GIS_personal_FS_2015.pdf

Hannah Bast's lectures on route planning algorithms:
https://ad-wiki.informatik.uni-freiburg.de/teaching/EfficientRoutePlanningSS2012

I don't know if any of these are interesting for the immediate purpose of the project, but there are several other pointers that I could add here if you'd like.

**Comment by mraross** [comment]
Thanks for the links PayasR! We are interested, particularly in time-dependent, multiple constraint (e.g., vehicle weight, height, width, length) routing. 

Some recent interesting links are:

Faster and Better Nested Dissection Orders for Customizable Contraction Hierarchies
https://arxiv.org/pdf/1906.11811.pdf

**Comment by mraross** [comment]
A general heuristic for vehicle routing problems
https://www.iro.umontreal.ca/~ferland/Seminars/Local_search/Pisinger,Ropke_ALNS_2007.pdf

**Comment by mraross** [comment]
Space-efficient, fast, and exact routing in time-dependent road networks
https://arxiv.org/pdf/1910.12726.pdf

**Comment by mraross** [comment]
Alternative multicriteria routes
https://epubs.siam.org/doi/pdf/10.1137/1.9781611975499.6

**Comment by mraross** [comment]
Time dependent route planning under multiple objectives
https://www.cirrelt.ca/DocumentsTravail/CIRRELT-2019-01.pdf

**Comment by mraross** [comment]
Modelling costs of turns in route planning
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.24.8035&rep=rep1&type=pdf

**Comment by mraross** [comment]
Existing and emerging emergency vehicle routing problems
https://arxiv.org/pdf/1906.06750.pdf

**Comment by mraross** [comment]
Hazardous materials routing [ Feb 2020]
https://www.mdpi.com/1660-4601/17/3/1104/pdf

**Comment by mraross** [comment]
Dynamic transfer patterns for fast multi-modal routing
http://www.thomas-liebig.eu/wordpress/wp-content/papercite-data/pdf/liebig17.pdf

**Comment by mraross** [comment]
MapReduce-based shortest path
https://journalofbigdata.springeropen.com/track/pdf/10.1186/s40537-018-0125-8

**Comment by mraross** [comment]
Space-Efficient, Fast and Exact Routing in Time-Dependent Road Networks
https://drops.dagstuhl.de/opus/volltexte/2020/12947/pdf/LIPIcs-ESA-2020-81.pdf

**Comment by mraross** [comment]
Multi-objective optimization using Stochastic Fractal Search (if it comes down to that)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7563052/

**Comment by mraross** [comment]
Garbage truck routing
https://www.mdpi.com/1660-4601/17/14/4963/pdf

**Comment by mraross** [comment]
Safe route planning
- potential source of road safety metrics that benefits all drivers
https://csce.ucmss.com/cr/books/2018/LFS/CSREA2018/IKE3527.pdf

**Comment by mraross** [comment]
Evacuation route planning
https://www.researchgate.net/publication/308600547_Improved_Algorithms_for_the_Evacuation_Route_Planning_Problem

**Comment by mraross** [comment]
Framing algorithms for approximate multicriteria shortest paths
https://drops.dagstuhl.de/opus/volltexte/2020/13147/pdf/OASIcs-ATMOS-2020-11.pdf

**Comment by mraross** [comment]
Towards Alleviating Traffic Congestion: Optimal Route Planning for Massive-Scale Trips
https://www.ijcai.org/proceedings/2020/0470.pdf

**Comment by mraross** [comment]
Space efficient, fast, and exact route planning in time-dependent road networks
https://www.mdpi.com/1999-4893/14/3/90/pdf

**Comment by mraross** [comment]
A Fast and Tight Heuristic for A* in Road Networks
https://arxiv.org/pdf/1910.12526.pdf

**Comment by mraross** [comment]
Route planner uses the jsprit open source library for solving the TSP (e.g. optimal ordering of stops in a single route). jSprit uses the Ruin and recreate algorithm. Here's a discussion of Ruin and recreate algorithm in jSprit repo:
https://github.com/graphhopper/jsprit/blob/master/docs/Meta-Heuristic.md

Original paper on Ruin and recreate algorithm (2000)
http://polymorphe.free.fr/cours/ia/tsp/schrimpf-record_breaking_opt_ruin_recreate.pdf

Slack induction by string removal for VRP (2018). Recent improved implementation of Ruin and Recreate.
https://lirias.kuleuven.be/retrieve/545845

A general heuristic for VRP problems
https://backend.orbit.dtu.dk/ws/portalfiles/portal/3154462/A+general+heuristic+for+vehicle+routing+problems_TechRep_Pisinger_Ropke.pdf
