### ISSUE TITLE
GDF Test Case 15 fails with crossing cost multiplier of 1.1

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#250]
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/6c67fe50-fd15-4eff-9bae-50456af7221c)

**Comment by mraross** [comment]
If I set the crossing cost multiplier to 1.2, the test succeeds.

![image](https://user-images.githubusercontent.com/11318574/77583164-d626a880-6e9d-11ea-97f4-fe81ce5477b1.png)

**Comment by cmhodgson** [comment]
wasn't the failure at a XingCost Multplier of 1.1, not 1.5? it seems to work at 1.5...

**Comment by mraross** [comment]
Yes, you're right. I corrected the issue title. A multiplier of 1.1 failed. I just successfully reran all GDP test cases with a multiplier of 1.2. Just going to rerun some other test cases and we might have a solution.

**Comment by mraross** [comment]
Multiplier of 1.2 works with https://github.com/bcgov/ols-router/issues/242

![image](https://user-images.githubusercontent.com/11318574/77586650-cc07a880-6ea3-11ea-8d3b-e8a26552d9f9.png)

**Comment by mraross** [comment]
Multiplier of 1.2 works the same as 1.1 on all cases in https://github.com/bcgov/ols-router/issues/245

**Comment by mraross** [comment]
Router configuration changed to use crossing multiplier of 1.2
