### ISSUE TITLE
interesting cases

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#251]
A bestiary of interesting routings

**Comment by mraross** [comment]
Doesn't take Front St in New Westminster
4811 No 8 Rd, Richmond, BC
901 Colborne St, New Westminster, BC

![image](https://user-images.githubusercontent.com/11318574/77593330-44289b00-6eb1-11ea-8425-c643a4406860.png)

**Comment by gleeming** [comment]
The reverse route doesn't take it either, however there is no access from Front St to McBride Blvd so a pretty substantial detour is required if Royal Ave is not used.

**Comment by gk-tl** [comment]
Complete. Thank you.
