### ISSUE TITLE
Performance test on Test

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#252]
Ran 30 random origin/destination pair route requests in the Metro Van area using location services in action and router and geocoder in test as follows:

https://bcgov.github.io/ols-devkit/ols-demo/index.html?rt=tst&gc=dlv

Raw execution times (in ms): 80,20,185,1820,199,267,264,237,238,2,78,52,45,152,223,179,73,19,33,66,282,266,262,269,90,17,257,4,201,299

Used calculator.net to compute stats on raw execution times:
https://www.calculator.net/statistics-calculator.html

and here's the results:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/4e97a20c-9e96-4526-b506-2230ace5934d)

**Comment by mraross** [comment]
Ran 30 random origin/destination pair route requests from across the province using location services in action and router and geocoder in test as follows:

https://bcgov.github.io/ols-devkit/ols-demo/index.html?rt=tst&gc=dlv

Raw execution times (in ms): 


Used calculator.net to compute stats on raw execution times:
https://www.calculator.net/statistics-calculator.html

and here's the results:

**Comment by alixcote** [comment]
Re-closing.
