### ISSUE TITLE
U-turn through a no u-turn restriction

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#253]
1308 Taylor Way, West Vancouver, BC
765 Park Royal North, West Vancouver, BC

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/56f795db-1d05-4c3e-9678-b7b363c94060)

**Comment by gleeming** [comment]
Can't replicate.  Did you have turn restrictions turned off?

**Comment by mraross** [comment]
Neither can I.

![image](https://user-images.githubusercontent.com/11318574/77666515-4b49ba80-6f3e-11ea-99ca-b82dd2c29660.png)

**Comment by mraross** [comment]
Verified in Test
