### ISSUE TITLE
Some ramps not classified as truck routes

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#254]

**Comment by mraross** [comment]
910 Handsworth Rd, District of North Vancouver, BC
103 29th St, West Vancouver, BC

![image](https://user-images.githubusercontent.com/11318574/75300683-8ba60380-57ed-11ea-8d38-007a2bba80c3.png)


![image](https://user-images.githubusercontent.com/11318574/75300641-674a2700-57ed-11ea-904f-b609d0439118.png)

**Comment by mraross** [comment]
Taylor Way Onramp
1101 W 1st St, District of North Vancouver, BC
4711 Woodley Dr, West Vancouver, BC

![image](https://user-images.githubusercontent.com/11318574/75300804-e17aab80-57ed-11ea-8255-4736eb363e85.png)

**Comment by mraross** [comment]
Al Tabbernor wrote (in issue )
After some discussion with @gk-tl we came up with a (hopefully) simple rule.  In the case of freeway or highway on/off ramps, if the ramp serves as a connection between two designated truck routes then we should classify that on/off ramp as a truck route.  If a freeway or highway on/off ramp connects a truck route to a non-truck route (or vise versa) we should classify that on/off ramp as a non-truck route.

For example the highlighted ramp below should be re-classified as a truck route.
![image](https://user-images.githubusercontent.com/59742145/77127764-fae8cf00-6a0a-11ea-916d-0178e248896f.png)

While the highlighted ramp in this case **_should not_** be a truck route:
![image](https://user-images.githubusercontent.com/59742145/77127811-29ff4080-6a0b-11ea-9c08-3a2d427cd520.png)

**Comment by mraross** [comment]
Graeme Leeming wrote (in issue  ):

I have now included these cases as part of a ticket batch for GeoBC, hopefully to be updating in the April ITN release. In our initial reconciliation of truck routes from Translink we deliberately did not extend designations to highway routes within the MVRD. The Lion's Gate Bridge, for example, is explicitly not a truck route despite being part of route 1A and 99.

If there is an official Translink or MoTI policy for associating truck routes with highway ramps, it would be useful for all to understand how this attribute should be managed and updated in the ITN.

**Comment by mraross** [comment]
Taylor Way offramp verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82839280-b69f0280-9e83-11ea-9aaa-04739a1a417f.png)

**Comment by mraross** [comment]
Taylor Way onramp verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82839665-fc0fff80-9e84-11ea-8f08-6826252eb867.png)

There is now a new issue with the unnecessary loop at the end. Lowering the truck route multiplier fixes the issue but not in an acceptable way since the multiplier has to be constant for all queries:

![image](https://user-images.githubusercontent.com/11318574/82839782-5c9f3c80-9e85-11ea-9229-74bff067eac0.png)

**Comment by gk-tl** [comment]
Hopefully, ticket #281 addresses the new issue.

**Comment by mraross** [comment]
verified in test
