### ISSUE TITLE
Can't route into Delta Port Entrance --

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#260]
Vanterm -- Stewart St, Vancouver, BC
Delta Port Entrance -- Roberts Bank Rd, Delta, BC

Get a No Route Found error

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/5974111c-8a50-41a1-ac38-f76da57feea4)

Clicking on the Delta Point entrance doesn't work either.
Routing from Delta Point Entrance -- works. So does routing into Delta Port Exit .

**Comment by gleeming** [comment]
This is caused from missing roads in ITN at Robert's Bank -- something I reported to GeoBC and looks to be updated in the pre-April road release.  I'll have to confirm the fixes work properly for routing once the April data is reconciled and loaded into the route planner.

**Comment by mraross** [comment]
Ok, that's fine. Glad it was a data problem and not a routing problem.

**Comment by gleeming** [comment]
Delta port entrance is now accessible after GeoBC fixed a geometry connection issue.
ITN truck routes and roads in this area may be incomplete and should be reviewed by Translink for any additional changes.

**Comment by mraross** [comment]
Verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82836706-e8ac6680-9e7b-11ea-9a56-c97efcbb0d37.png)
