### ISSUE TITLE
Router ignores turn restriction between overpass segments

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#263]
A complicated overpass situation on Robert's Bank Rd in Tsawwassen has three segments meeting at an overpass over two lower segments, and there is a turn restriction required. This turn restriction is able to be created in the turn restriction editor, it is handled correctly in the Routeable BC Maker, but the Router itself ignores it on startup due to a logic error caused by the overpass situation.

This particular problem is demonstrated by a route 
from: 49.03365,-123.14605 
to: 49.02628,-123.15443 
with follow truck route enabled (disabling it actually shows the correct route)

**Comment by mraross** [comment]
Verified in delivery!

And, thanks to a related data correction in ITN, you can now route from;

   Vanterm -- Stewart St, Vancouver, BC
to
    Delta Port Entrance -- Roberts Bank Rd, Delta, BC

The data error in March ITN prevented access to Delta Port Entrance.

**Comment by mraross** [comment]
Verified in delivery using May 2020 data
