### ISSUE TITLE
Test Case for  In truck resources, set default followTruckRoute=true [Router v2.1.2]

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#268]
Here's a test case for validating that router sets followTruckRoute=true for all truck resources. For more details, see: https://github.com/bcgov/ols-router/issues/256

1.	Explicit setting of followTruckRoute=true
https://router-dev.pathfinder.gov.bc.ca/truck/distance.html?points=-123.0739278%2C49.284965%2C-123.0692965%2C49.3049615&criteria=fastest&followTruckRoute=true

2.	No followTruckRoute parameter on request. Expect distance to be the same as that in first request
https://router-dev.pathfinder.gov.bc.ca/truck/distance.html?points=-123.0739278%2C49.284965%2C-123.0692965%2C49.3049615&criteria=fastest

3.	Explicit setting of followTruckRoute=false. Expect distance to be different than two previous requests.
https://router-dev.pathfinder.gov.bc.ca/truck/distance.html?points=-123.0739278%2C49.284965%2C-123.0692965%2C49.3049615&criteria=fastest&followTruckRoute=false

4.	Repeated first three requests using route.html instead of distance.html

5.	Repeated first three requests using directions.html instead of distance.html.

**Comment by mraross** [comment]
Verified in production

**Comment by alixcote** [comment]
Re-closing.
