### ISSUE TITLE
Test for turn-restriction on overpass bug [Router 2.1.2]

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#275]
This request should find a route through an intersection on an overpass:

https://router-dev.pathfinder.gov.bc.ca/truck/route.json?points=-123.14605,49.03365,-123.15443,49.02628&criteria=fastest&followTruckRoute=True

**Comment by mraross** [comment]
From Chris hodgson:

A complicated overpass situation on Robert's Bank Rd in Tsawwassen has three segments meeting at an overpass over two lower segments, and there is a turn restriction required. This turn restriction is able to be created in the turn restriction editor, it is handled correctly in the Routeable BC Maker, but the Router itself ignores it on startup due to a logic error caused by the overpass situation.

This particular problem is demonstrated by a route
from: 49.03365,-123.14605
to: 49.02628,-123.15443
with follow truck route enabled (disabling it actually shows the correct route)

**Comment by mraross** [comment]
Ran test request against Router 2.1.3 and it failed to find a route:

https://router-dev.pathfinder.gov.bc.ca/truck/route.json?points=-123.14605,49.03365,-123.15443,49.02628&criteria=fastest&followTruckRoute=True

so do setting followTruckRoute to False as in this request:

https://router-dev.pathfinder.gov.bc.ca/truck/route.json?points=-123.14605,49.03365,-123.15443,49.02628&criteria=fastest&followTruckRoute=True

**Comment by cmhodgson** [comment]
I believe the other part of the fix for this is in the April ITN data which it does not appear the DLV router is using. Graeme, Brian, can you confirm?

**Comment by gleeming** [comment]
Works in RRI dev April data.  Data in deliv looks to be March

**Comment by BK01** [comment]
Correct. router-dev.api.gov.bc.ca is using March data. We still need to update the RBC Maker to work with the new minIO bucket location.

**Comment by alixcote** [comment]
Re-closing.
