### ISSUE TITLE
In ACDF, a route from anywhere to Saanich Peninsula Hospital results in route not found

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#278]
In ACDF, a route from anywhere to Saanich Peninsula Hospital at 2166 MOUNT NEWTON CROSS ROAD, SAANICHTON  results in a Route not found error.

We did a test in betweenPairs demo app which confirmed correct operation of Route Planner as follows:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/77e434fc-e9f0-4c63-a560-775cd809ab47)

**Comment by mraross** [comment]
Brian Kelsey wrote:


addressString | X | Y
-- | -- | --
6225 216 Street, Langley | -122.6260137 | 49.116289
2166 MOUNT NEWTON CROSS ROAD, SAANICHTON | -123.4070876 | 48.5960169
200 - 5503 - 206TH STREET,   Langley | -122.6518267 | 49.1027399

**Comment by NicoledeGreef** [comment]
imapbc puts 2166 mount newton cross road here:
![image](https://user-images.githubusercontent.com/26335003/80849811-bdf92600-8bcd-11ea-8cfd-7744eb1d5a31.png)
but the hospital with that address is actually the pink parcel (Federal Ownership) whereas the yellow parcel are Privately owned.
the parcels have different PIDs.  i am confused...

**Comment by mraross** [comment]
We just take the parcelPoint the muni (Central Saanich) gives us. In any case, the issue resolution is the same because the parcel centroid of the correct parcel is also beyond snapping distance of the road.

**Comment by NicoledeGreef** [comment]
the ACDF addresses are being run through the ALE once a month before re-loading.  what does the address list editor use - accesspoint as opposed to parcelpoint?

**Comment by mraross** [comment]
ALE returns parcelPoints. You could use the batch geocoder. It allows you to specify a locationDescriptor of accessPoint. Saanich Peninsula Hospital is probably the only location in your list on that big a parcel so you could just plug the access point coordinates from this ticket (see above) into your csv file after you've processed it in the ALE. But, to be safe, and avoid confusion, batch geocoder is better.

**Comment by NicoledeGreef** [comment]
maybe that's the issue then.  i'll try the batch geocoder and see if it fixes the issue.

**Comment by NicoledeGreef** [comment]
accessPoint (red dot)versus parcelPoint (pin) as geocoded by address search in imapBC:

![image](https://user-images.githubusercontent.com/26335003/81025430-7d96e380-8e2b-11ea-9876-20b9e25ae1bd.png)

Testing the data once it's loaded to DLV and TST tomorrow.

**Comment by mraross** [comment]
Red dot looks good for routing!

**Comment by NicoledeGreef** [comment]
locationDescriptor of "accessPoint" when geocoding has fixed the Saan Pen Hospital issue the end users were seeing in ACDF.  thanks for the assistance in tracking down the cause of the issue.

**Comment by mraross** [comment]
Woo hoo!!

**Comment by mraross** [comment]
Verified in production
