### ISSUE TITLE
GDF Test 13 failed in delivery with April 2020 data

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#279]
GDF Test 13
Starting from a strata road
925 Main St, West Vancouver
1564 Argyle Ave, West Vancouver

in production with march 2020 data:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/6a537c36-5682-461e-9b7d-49db2012d300)

in delivery with april 2020 data:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/9efcff10-9d18-4e34-82a9-66012721d5ff)

**Comment by mraross** [comment]
This happened previously because of a strata road GDF factor that was too high. See:

https://github.com/bcgov/ols-router/issues/239

The strata road GDF factor for trucks used in this test is 1.1 which is lower than the 1.2 used to fix this problem last time.

**Comment by cmhodgson** [comment]
It works if you tune down the multiplier. The speed limit on that segment is 20 or 25 km/h, which means that you can travel 18 times further on a 50km/h road that is a truck route to avoid travelling on that segment. This is a general problem with using "fastest" when what we really mean is "shortest, but avoid turns" . I guess if this worked in the previous data it must be either some change to the segments (eg. speed limit) or an LDF issue. I hadn't previously considered home much speed limits affect the multiplier in a fastest scenario like this, I wonder if there isn't something smarter we could do.

**Comment by mraross** [comment]
I turned it down to 1.0 which is as low as you can go and it still doesn't  fix the problem:

![image](https://user-images.githubusercontent.com/11318574/81626859-b4cc3e00-93b1-11ea-98c7-2e484318e954.png)

**Comment by mraross** [comment]
Agreed but in the meantime, Graeme can you please determine what's changed?

**Comment by gleeming** [comment]
In March we provided the full cut of router-ready input data to DataBC.  In April we only supplied the custom reconciled files for RoutableBC Maker, and DataBC generated the build.

I am concerned that something is odd with the result from April because there should be a U-turn restriction at the far north of the path preventing that route (Taylor Way just past TCH).  If it were in your router, I suspect that the test would pass.

Can you search your March and April turn_restrictions.csv files for 164221|44361|164401|44333|2554773 -- this should be the EDGE_NODE_SET value for a uturn restriction at Taylor Way.  Also how many rows are in your April turn_restrictions.csv file?

**Comment by BK01** [comment]
The following EDGE_NODE_SET value is not found in DataBC's March or April turn_restriction or turn_classes file (164221|44361|164401|44333|2554773).

Row counts:

**March:**
turn_restrictions.csv = 19,803
turn_classes.csv = 1,249,349

**April:**
turn_restrictions.csv = 19,803
turn_classes.csv = 1,275,702

**Comment by gleeming** [comment]
There was a turning lane added in April, so the March data actually had a different version of this particular uturn restriction: 164221|44361|164401|44333|166260.  This may be useful as your April counts should not be the same as the March -- I suspect they are the same file (check file dates and search for the previous restriction string).  Our April turn_restrictions,csv file has 20987 rows.

**Comment by BK01** [comment]
Confirmed. The two files are the same and both have the same edge-node-set value.

**Comment by cmhodgson** [comment]
So just to be clear, that is bad, and means that you either didn't copy the new turn_restrictions.csv file from the output of the routeablebc maker to the dlv data directory, or that you ran the routeableBC make against the old data. Given that you have a new, different, larger, turn_classes.csv, it seems likely that you did run routeableBC maker against the new data, meaning the issue may be just somewhere in the copying?

**Comment by BK01** [comment]
We will trace back the file to the original April 23rd delivery of the turn file and compare to the file in the router start-up location. I agree that it appears the routeablebc maker ran against new data but with the March turn file.

**Comment by gleeming** [comment]
That delivery also included the LDF, truck notice, events and GTFS files.  These should all end up in the router start-up location.  In addition the GTFS set (with custom turn restrictions) should also be part of the routableBC maker inputs.

**Comment by BK01** [comment]
@mraross The issue should now be resolved. Verified using April data with the DLV router at https://ols-demo.apps.gov.bc.ca/index.html?rt=dlv (Geocoder PROD used as Geocoder DLV is being prepped at street-level)

**Comment by mraross** [comment]
GDF Test Case 13 now succeeds in delivery  using:

https://ols-demo.apps.gov.bc.ca/index.html?rt=dlv

as suggested by Brian above.  Thanks Brian.

**Comment by BK01** [comment]
New file details.

March:
turn_restrictions.csv = 19,803
turn_classes.csv = 1,249,349

April:
turn_restrictions.csv = 20,987
turn_classes.csv = 1,275,702

**Comment by gleeming** [comment]
The April counts match those we generated.  For the May data, I have already run the suite of tests against our dev server.  When DataBC processes it later this month in delivery I will run the same tests and make sure they have identical results.
