### ISSUE TITLE
Review Open Street Map data model and attribute schemas related to navigation

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#28]
@mraross commented on [Tue Jun 05 2018](https://github.com/bcgov/api-specs/issues/342)

Of particular interest is the attribute schema used by TeleNav for use in their Scout in-car routing app.

**Comment by gleeming** [comment]
A good overview of the tags can be found at https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Telenav

**Comment by mraross** [comment]
Here's something on turn restriction QA:

"The ImproveOsm plugin has a Turn Restriction layer that points at probably missing turn restrictions."
https://wiki.openstreetmap.org/wiki/Relation:restriction#Members

**Comment by alixcote** [comment]
Not planning in car navigation. If it comes up more, we can re-evaluate.
