### ISSUE TITLE
Add support for timed notifications

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#295]
A timed notification is a notice that has an effective time period. During this period, the notice should be displayed on the appropriate leg of the best route in turn-by-turn directions. A notification doesn't affect the computation of best route. This is required by TransLink. Notifications sourced from a road restriction data service need to support a notificationOnly flag for the route planner to know that a road restriction is simply a notice and should not be used to affect best route.

**Comment by cmhodgson** [comment]
This feature has been implemented at Translink's request. It has not yet been committed but is only 6 lines of straightforward code that can only effect the truck notice handling.
