### ISSUE TITLE
Router directions are not showing prefix or suffix directionals for street names

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-router#309]
Street names in router directions include the name body and name types but no directionals.  For example
  West Kent Ave N, Vancouver, BC
    to
  Aisne St, Vancouver, BC
should output names with West Kent Ave **N** and **SW** Marine Dr.

**Comment by cmhodgson** [comment]
There was an error in the code that reads the street names in, it was reading "street_dir" instead of "street_direction". This is now fixed locally.

**Comment by cmhodgson** [comment]
The fix for this has not been committed yet but is 2 easily verifiable lines.

**Comment by BK01** [comment]
Validated in v2.1.4. Migrated to PROD.
