### ISSUE TITLE
In functional router, add support for designated vehicle routes

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#31]
@mraross commented on [Fri Jun 23 2017](https://github.com/bcgov/api-specs/issues/217)

For example, a truck route must follow designated truck routes; in an evacuation, all vehicles must follow designate evacuation routes. Emergency vehicles may route through roads restricted to emergency vehicles; other vehicles can't.

The BC Ministry of Tranportation and Infrastructure describes designated routes as a preference ranking where each road segment has a low, medium, or high preference (or attraction) for certain types of vehicle.

Route designations may come from the BC Digital Road Atlas or directly from the BC Ministry of Transportation and Infrastructure and BC municipalities

---

@mraross commented on [Sat Feb 03 2018](https://github.com/bcgov/api-specs/issues/217#issuecomment-362855329)

This looks like a promising approach:

Fast shortest path with parameterized costs
https://arxiv.org/pdf/1509.03165.pdf

**Comment by cmhodgson** [comment]
Support has been added for truck routes, using the truck route flag in ITN. If followTruckRoute=true, then all non-truck routes have their cost multiplied by a default of 2; if you provide a truckRouteMultiplier=X then the cost of non-truck routes is multiplied by X.

**Comment by mraross** [comment]
The truckRouteMultiplier is intended for use in understanding the its effect on routing and will likely be dropped from the first production release of the geocoder.
