### ISSUE TITLE
Vehicle-type specific turn restrictions don't work in some cases

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-router#312]
The RouteableBC Maker needs to be fixed to properly handle turn restrictions for specific vehicle types (eg. truck-only).

**Comment by cmhodgson** [comment]
This is fixed in my local code and has been tested on our dev server. It has not yet been committed but is a one-line fix.

**Comment by BK01** [comment]
Validated with BC Route Planner 2.1.4 in DLV using that latest data prepared following the RouteableBC Maker update.

**Comment by gleeming** [comment]
Here's a test case for confirming limited access to Coquitlam Mainline.  Post-fix, only truck mode routing should succeed.  This models a private access point that should only be available to trucks during certain times, and never to other vehicles.
Start: 49.33698,-122.77170
End: 49.37980,-122.77651

**Comment by BK01** [comment]
Test case above has been validated in both DLV and TEST (latest data).

**Comment by BK01** [comment]
Test case also validated in the PROD environment.
