### ISSUE TITLE
What is the road segment weighting formula used by the current route planner?

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#326]
On Thu, Aug 26, 2021 at 3:44 PM Ross, Michael RA CITZ:EX <Michael.RA.Ross@gov.bc.ca> wrote:
Hi Chris,
What Is the actual formula for calculating road segment weighting from the truck route multiplier, global and local distortions fields, maxSpeed, and segment length?

**Comment by alixcote** [comment]
Documented in LOC Confluence. Closing.
