### ISSUE TITLE
In functional router, add support for turn restrictions related to vehicle dimensions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#33]
@mraross commented on [Wed Mar 07 2018](https://github.com/bcgov/api-specs/issues/309)

Some turns and S-curves in road segments are too tight for vehicles over a certain length or width.

**Comment by mraross** [comment]
Turn restrictions for oversized vehicle can be automatically computed for the following cases:
If the angle between two road segments is less than 30 degrees, a turn is not allowed.
If the turn angle  is less than 70 degrees and involves a ramp, the turn is not allowed.

Source: p. 26 - OnRouteBC Business requirements

**Comment by cmhodgson** [comment]
We have implemented the 30 degree turn restriction for vehicles over 12.5 meters. I don't believe that the ITN "ramp" road class corresponds to the same ramp concept intended by the restrictions. We can add further such restrictions easily enough in the future.
