### ISSUE TITLE
make MAX_SNAP_DISTANCE a query time parameter

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ols-router#332]
**Is your feature request related to a problem? Please describe.**

## Routing challenges in the Peace River region: 
* Oil wells (?) are not on demographic roads. 
* Commercial vehicles need to obtain routes from the well to their destination.
* If the well is outside of the “snap-to-grid” tolerance, the route planner will not find a route.
* Non demographic roads are not (or may not?) be included in the route planner so the route planner cannot generate routes that include these.

The parties involved have scripted "work arounds" which they can continue to do, however, the workaround add complexity.

**Describe the solution you'd like**

There is no query time parameter which can set the tolerance distance for a route query.
A query time parameter would simplify, potentially, finding routes when the starting point is more than the current snap-to tolerance (1km)

**Describe alternatives you've considered**

The client does have work around and can continue to do this however this adds complexity.
We are exploring whether changing the tolerance can work.

**Additional context**

**Comment by dkelsey** [comment]
LOC-2635

**Comment by cmhodgson** [comment]
Adding a query-time parameter for the tolerance would not be hard to do, there would be more work in testing and deployment than in the change itself. 

It would be interesting to know what their work-around is and if it also suffers from the issues that we expect if we increase the snap tolerance, eg. the nearest routable road segment is not necessarily the most accessible via existing resource roads.

Maybe there are some "major" resource roads that should be add to the routing network for truck queries and/or when a new "allow resource roads" parameter is turned on. We know there are too many resource roads to include them all, and they are of unknown accessibility and accuracy. Perhaps when the source or destination point is nearest to a major resource road then the they could be allowed automagically? They probably shouldn't be allowed in the middle of a route, only at either end. But that is all based on identifying some subset of resource roads that are significant, current, and accurate, and adding them to the routing network. Maybe there are just a relatively small number of particular, active mines or other sites that need their access roads added?

**Comment by BK01** [comment]
Duplicate issue. Snap tolerance parameter covered in (#356). Adding a small subset of non-demographic roads will be covered in a separate issue.
