### ISSUE TITLE
Add support for finding routes that minimize assisted maneuvers

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#39]
@mraross commented on [Mon Jun 04 2018](https://github.com/bcgov/api-specs/issues/340)

A assisted maneuver is a road restriction that can be mitigated by special activities. An example is allowing a wide load on a road segment by closing opposite direction and using a flag-person. MoTI permit clerks must approve all assisted maneuvers.

Add a new resource that finds a route that minimizes  road restriction violations. The result should include a list of all road segments with mitigated restrictions. This may require multi-criteria optimization.

**Comment by alixcote** [comment]
We think this will be replaced by more specific onRoute requirements and the ability to exclude specific types of restrictions.
