### ISSUE TITLE
In functional router, add support for region-based road  restrictions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#40]
@mraross commented on [Mon Jun 04 2018](https://github.com/bcgov/api-specs/issues/339)

While a loaded vehicle may fit on a given road segment, permitting regions may not allow such vehicle dimensions on that segment. There are multiple permitting regions in the province (e.g., Peace District, Lower Mainland, Lower Mainland OAH corridors).

**Comment by alixcote** [comment]
Will be replaced with road segment specific restrictions from RDM or other sources.
