### ISSUE TITLE
In functional router, add support for area-based road restrictions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#49]
@mraross commented on [Fri Jan 19 2018](https://github.com/bcgov/api-specs/issues/284)

Road travel restrictions may be specified on an area-wide basis instead of on a segment by segment basis. For example, a transport permitting authority may specify that certain road classes within its area of authority should be not be travelled on by certain vehicle profiles due to heavy rains.

---

@mraross commented on [Sat Feb 03 2018](https://github.com/bcgov/api-specs/issues/284#issuecomment-362859488)

This looks like a promising approach to implementation:

Fast shortest path with parameterized costs
https://arxiv.org/pdf/1509.03165.pdf

**Comment by alixcote** [comment]
Closing. Will be implementing restrictions by road segment. Can re-open if clients request.
