### ISSUE TITLE
Add support for configurable vehicle profiles

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#51]
@mraross commented on [Fri Jun 23 2017](https://github.com/bcgov/api-specs/issues/218)

Instead of supplying vehicle dimensions explicitely, allow a user to pick a vehicle profile that supplies the needed dimensions and preferences. For example, an SUV can handle more road surfaces than a car. Different types of truck may also be defined. Graph Hopper and other APIs support vehicle profiles.

**Comment by alixcote** [comment]
This could be an app configuration that knows the vehicle type and sends the params to the router.
