### ISSUE TITLE
Find a traffic simulator that can generate the real-time events necessary to validate the time-dependent routing algorithm

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#6]
@mraross commented on [Tue Jun 05 2018](https://github.com/bcgov/api-specs/issues/343)

It doesn't have to be realistic, just plausible. This will insulate us from lack of real data in the early period of the project.

 Event types should include:
- road currentSpeed
- current and planned road closure of a given road segment, corridor,  or geographic area
- current and planned lane closure of a given road segment, corridor or geographic area
- mandated speed reduction (e.g., as a percentage of max speed) on a given road segment, corridor, or geographic area. 

---

@mraross commented on [Tue Jun 05 2018](https://github.com/bcgov/api-specs/issues/343#issuecomment-394913787)

For a simple way to simulate traffic congestion, see section 5.1 Simulating traffic in
http://drops.dagstuhl.de/opus/volltexte/2017/7897/pdf/OASIcs-ATMOS-2017-3.pdf

Fancier approaches:

Using a Traffic Simulator for Navigation Service
https://people.eng.unimelb.edu.au/etanin/gis17c.pdf

---

@mraross commented on [Wed Jun 06 2018](https://github.com/bcgov/api-specs/issues/343#issuecomment-395258874)

OpenTraffic includes a real-time traffic stats generator, a real-time traffic data exchange format, and OSMLR, a set of OSM tile with traffic speeds.
 https://github.com/opentraffic/otv2-platform

open traffic stats from other jurisdictions
https://github.com/graphhopper/open-traffic-collection

Tom Tom real-time traffic data
https://www.tomtom.com/lib/img/REAL_TIME_TRAFFIC_WHITEPAPER.pdf

For Velocity Fields and Congestion Spreading After Incidents, see section 4.3 in:
https://www.cl.cam.ac.uk/research/srg/opera/publications/papers/2011LNCS6875.pdf

Real-Time Traffic Information Management using Stream Computing
https://pdfs.semanticscholar.org/2a59/510b3adea158588928cd813915dcd7bc0fad.pdf

Real Time Traffic Monitoring System Using Crowd Sourced GPS Data
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.866.2007&rep=rep1&type=pdf

---

@mraross commented on [Mon Jun 11 2018](https://github.com/bcgov/api-specs/issues/343#issuecomment-396017112)

Traffic congestion metrics
http://www.tac-atc.ca/sites/default/files/site/doc/Bookstore/defining-measuring-congestion.pdf
http://www.tac-atc.ca/en/publications/ptm-dmuc-e

Circular traffic simulator
http://www.traffic-simulation.de/

Simulation of Urban Mobility (SUMO)
 - supports OSM format
http://www.dlr.de/ts/en/desktopdefault.aspx/tabid-9883/16931_read-41000/

Toward realistic urban traffic congestion experiments using DFRouter
 - a component of SUMO
http://www.mdpi.com/1424-8220/17/12/2921/pdf

Flow architecture and benchmarking for reinforcement learning in traffic control
 - uses SUMO
https://arxiv.org/pdf/1710.05465.pdf

IEEE ITSC 2018 SUMO workshop
https://www.ieee-itsc2018.org/uploads/5/0/3/9/50391481/tutorial_on_simulation_of_urban_mobility__sumo__v2.pdf

TraffSim: A traffic simulator for investigations of congestion minimization through dynamic vehicle rerouting
 - supports OSM format
http://ijssst.info/Vol-15/No-4/paper5.pdf

The impact of GPS enabled shortest path routing on mobility: a game-theoretic approach
http://ijssst.info/Vol-15/No-4/paper5.pdf

Proactive vehicle rerouting strategies for congestion avoidance 
https://web.njit.edu/~borcea/papers/dcoss12.pdf

Traffic recovery time estimation under different flow regimes
-  predicts post-incident traffic recovery time based on traffic intensity, incident duration, and incident severity (ratio of lanes closure).
https://ac.els-cdn.com/S2095756415000653/1-s2.0-S2095756415000653-main.pdf?_tid=8a3b4824-0fed-4d44-91d4-3ad3d192ccb8&acdnat=1528518266_beb44b5515ab38020a97d061f4dddd31

Multi agent, transport simulation
https://matsim.org/

Integration of information patterns in the modelling and design of mobility management systems
https://arxiv.org/pdf/1707.07371.pdf

Towards a socially optimal multi-modal routing platform
https://arxiv.org/pdf/1802.10140.pdf

Comparison of traffic simulators
https://www.matec-conferences.org/articles/matecconf/pdf/2016/44/matecconf_ictte2016_05002.pdf

**Comment by alixcote** [comment]
Documented in LOC Confluence. Closing.
