### ISSUE TITLE
Route point snaps to far-away ferry segment

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#62]
from 330 View Point Rd, Esquimalt, BC
    to 6340 West Lake Shoreline, Nelson Island, BC

NG  0.185 sec
GH No route exists

Looks like NG is using a nearby ferry route to snap the stop point to.

**Comment by mraross** [comment]
1 km? It would be nice to have a global parm for maxSnap in the geocoder admin app.

**Comment by cmhodgson** [comment]
The default maximum snapping distance should be a configurable application parameter, set initially to 1000m. The maximum snapping distance should also be configurable at query time using a new parameter "maxSnapDist", where a value of 0 or less means "no maximum snapping distance".

Additionally, we should never snap points to ferry routes, bridges, or tunnels. However it may be difficult to reliable identify bridges and tunnels as they are not road classes (like ferries are).

**Comment by mraross** [comment]
Instead of maxSnapDist, how about maxSnap or maxSnapDistance for the query parameter name. 

As for identifying bridges and tunnels, isn't the streetQualifier consistently populated in DRA?

**Comment by mraross** [comment]
Verified in dev
