### ISSUE TITLE
In Route Planner Sandbox, introduce the concepts of explicit origin, destination, and way points

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#80]
Introduce the concept of explicit origin, destination, and way points. Currently the first and last points in the list are implicitly origin/destination points and any other points are way points. The [Graphhopper demo app](https://graphhopper.com/maps/?point=48.428773%2C-123.358505&point=48.429492%2C-123.367378&locale=en-us&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) illustrates interaction using these concepts.

To be more specific, add support for the following map interactions:

3. Right-click on the map and select Set as start or Set as end from the popup menu. The clicked location is used to update the origin or destination point.

4. Right-click on the map and select Set as waypoint option from the popup menu. The clicked location is added as the last waypoint in the route.

5. Right-click on an origin, destination, or way point and select Delete option from the popup menu.

6. Right-click on a origin, destination, or way point and select copy to clipboard from the popup menu.

7. Right-click on the map and select copy to clipboard from the popup menu

Right-click is tap and hold on Android.

Current click-on-map behavior can stay the same.

Green and red icons in the route point list would be helpful too.

The Graphhopper demo app illustrates all these interactions except copy to clipboard.

**Comment by mraross** [comment]
Maybe we can replace reverse direction of route on its own icon in the left panel. That would make it more obvious that the waypoints will be reversed as well.

We wouldn't need copy to clipboard in the popup menu if a single click/tap  displayed the coordinates at the cursor position and copied them to the clipboard.

**Comment by alixcote** [comment]
We have this concept (slightly different UI) in the demo app now. Closing.
