### ISSUE TITLE
Improve realism of turn costs

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#84]
1. Improve handling of complex intersection crossing (e.g. not double-penalizing for 2 light impactors as part of a single logical intersection at a divided crossing)

2. Turns into heavy traffic (especially left even with no impactor) can sometime require a long wait.  Perhaps favour flow in the current direction, maybe apply a base turn cost as you would have to at least slow down for a 90 degree turn, e.g. local to arterial

3. Possibly expand the delay matrix to account for more groupings, 2-way vs 4-way stops, adjusted for speed limit, etc

**Comment by mraross** [comment]
1. Improve handling of complex intersection crossing (e.g. not double-penalizing for 2 light impactors as part of a single logical intersection at a divided crossing)

2. Turns into heavy traffic (especially left even with no impactor) can sometime require a long wait.  Perhaps favour flow in the current direction, maybe apply a base turn cost as you would have to at least slow down for a 90 degree turn, e.g. local to arterial

3. Add costs for left, right, and straight (no) turns. Take cross-street into account.

**Comment by alixcote** [comment]
This is now available in the route planner. We have left turn, right turn, yield, crossing costs, stop signs, etc. Closing.
