### ISSUE TITLE
Implement more of the open511 spec

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#85]
Find the quick wins among the following: 

1. Line String geometric extents 

2. Polygon geometric extents

3. Validate administrative area name

4. Expected Delay parameter
    - modify speed limit?
    - add new concept we might reuse for ferry scheduling?

5. Additional event states
    - ALL_LANES_OPEN
    - SINGLE_LANE ALTERNATING
    - SOME_LANES_CLOSED

6. Direction (e.g., N, S, E, W)

7. recurring_schedule cases

8. Event types
    - SPECIAL_EVENT
    - WEATHER_CONDITION
    - ROAD_CONDITION

**Comment by cmhodgson** [comment]
I have added support for any event with a point location and a +delay value.
