### ISSUE TITLE
In Routable BC Maker, add support for reading in scheduled road events from an Open511/GeoJSON format 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#88]

**Comment by cmhodgson** [comment]
The Routable BC maker does not read the Open511 events, this is done by the application itself. As the events would not be static, it doesn't make sense to do any pre-processing on them in the RouteableBC maker. The router application itself does now read in the events from a file in the Open511 geojson format, and supports some limited number of types of events. Specifically events which:
- have a point location (not a linestring)
- are either complete closures OR have a +delay parameter set
This support is in place now on the dev server.
