### ISSUE TITLE
in route planner, add a resource called ping that checks node health

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#91]
@mraross commented on [Fri Jun 01 2018](https://github.com/bcgov/api-specs/issues/336)

The resource should perform a simple distance along road network calculation between two known points and return an HTTP 200 response code with no body.

Example:

router.api.gov.bc.ca/ping

ping will be used by a watchdog timer in the API Gateway to determine node health.

**Comment by cmhodgson** [comment]
Done. Currently supports only get requests, I can't see why we would need to support POST (and Sonar prefers supporting only one type of request)

**Comment by cmhodgson** [comment]
Confirmed working in delivery.

**Comment by mraross** [comment]
Verified
